### ISSUE TITLE
Guaranteeing progression of the chain

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#10]
Once all slot owners have been slashed and thus deactivated, we should select a random block producer from them to immediately produce a macro block. Otherwise the blockchain will stop, because there are no candidates for block producers.

**Comment by brunoffranca** [comment]
Well observed. How about allowing misbehaving validators to keep producing blocks until the end of the epoch? They still get punished anyway and this way you don't run out of slot owners.
I know I was the one suggesting that misbehaving validators should be immediately barred from producing micro blocks, but in retrospect it was not well-thought out.

**Comment by jgraef** [comment]
I actually like the idea of blocking all slots of a misbehaving validator. In the normal case, this validator went offline. If we allow him to still be selected for block production, this will slow down the chain a lot. Although the slow down could be minimized by having an adaptive timeout.

And I think this mechanism is just meant as a last resort. Usually this should not happen, if we assume that 2/3 are actually behaving correctly. It's more for the case that e.g. the network is partitioned by e.g. an major internet outage and 2/3 can't be reached in any partition. Then everyone would get slashed, then skip to the macro block, and as soon as the network isn't partitioned anymore, they can create this "recovery" macro block.

Also, without slashing all slots of a misbehaving validator, it could still happen that the network ends up in this state.

**Comment by brunoffranca** [comment]
If it's only a last resort in case of a network partition, then you don't need it. For a view change to happen you need 2/3 to agree to it, that is impossible in a network partition.
That being said, it can't hurt to have an extra line of defense.

**Comment by jgraef** [comment]
> If it's only a last resort in case of a network partition, then you don't need it. For a view change to happen you need 2/3 to agree to it (in 2 rounds of signing), that is impossible in a network partition.
> That being said, it can't hurt to have an extra line of defense.

Ah yes, you're right. Still, we just want to avoid everyone from being blocked to produce blocks.
