### ISSUE TITLE
Assertion in MDBX 0.1.8

### ISSUE THREAD

**Issue by jsdanielh** [nimiq/core-rs-albatross#1014]
Updating `mdbx` to 0.1.8 as #1005 did, the code randomly an assertion:
```
nimiq-client: mdbx:9268: map_resize: Assertion `size_bytes == env->me_dxb_mmap.current' failed.
```
The issue looks much more reproducible when triggering the _Devnet Release Scenarios_.
As a temporal fix 7542732 reverts it back to 0.1.7.

**Comment by hrxi** [comment]
Upstream bug report: https://github.com/vorot93/libmdbx-rs/issues/16.

**Comment by hrxi** [comment]
Further upstream: https://gitflic.ru/project/erthink/libmdbx/issue/7.

**Comment by hrxi** [comment]
Upstream has fixed the bug and disabled debug assertions in release mode. You could try updating again.

**Comment by jsdanielh** [comment]
Cool, I'm testing #1134 to see if the issue is gone
