### ISSUE TITLE
Failed to parse client.toml 

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#1039]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### Error

Happens when uncommenting the `path`.

```Config file parsing error: unknown field `path`, expected one of `level`, `timestamps`, `tags`, `statistics`, `file`, `loki`, `rotating_trace_log`, `tokio_console_bind_address` for key `log` at line 239 column 1
  caused by
    unknown field `path`, expected one of `level`, `timestamps`, `tags`, `statistics`, `file`, `loki`, `rotating_trace_log`, `tokio_console_bind_address` for key `log` at line 239 column 1```

### General information

```
[log]
# Configure global log level.
# Possible values: "trace", "debug", "info", "warn", "error"
# Default: "info"
level = "debug"

# Define specific log levels for tags.
# Default: none
#tags = { BaseConsensus = "debug" }

# Specify whether timestamps should be included for log statements.
# Default: true
#timestamps = false

# Save log output to a file.
# If not specified, log to stdout.
# Default: none
file = "nimiq-client.log"

# Tokio console
# Default: None
#tokio_console_bind_address = "127.0.0.1:6669"

# Specify a rotating log file containing a trace log
# [log.rotating_trace_log]

# Set the path to the folder containing the log files
# Default: "~/.nimiq/logs"
path = "~/.nimiq/logs"

# Size of each log file
# Default: 50_000_000 (50 MB)
# size = 50_000_000

# Count of additional log files. The total log files count will be file_count + 2.
# Default: 3
# file_count = 2

# Loki target
# [log.loki]

# Loki server address
# Default: None
# url = "http://localhost:3100"

# Labels set on the log messages. There should only be a finite amount of
# different label values, and ideally very few labels. See the Loki
# documentation for details:
# labels = { host = "mine" }

# Extra fields added to each log message (e.g. to distinguish runs)
# extra_fields = { run = "e2f8e044-0067-4902-914f-261b7f500ba7" }
```

**Comment by sisou** [comment]
I believe you need to uncomment the config section header `[log.rotating_trace_log]`, because the `path` config belongs to it.
