### ISSUE TITLE
RPC Client: No closing handshake

### ISSUE THREAD

**Issue by faberto** [nimiq/core-rs-albatross#1057]
The RPC client does not close the correction correctly.

### Sample Command
`nimiq-rpc block-number`

### Server Log
`ERROR nimiq_jsonrpc_server | Websocket error: HTTP error: WebSocket protocol error: Connection reset without closing handshake `

**Comment by hrxi** [comment]
This is presumably the following TODO: https://github.com/nimiq/jsonrpc/blob/41d26fc1aa4fffde2ded7d4c187c9d693a588aed/nimiq-jsonrpc-client/src/websocket.rs#L59-L61.
