### ISSUE TITLE
RPC Client should print useful errors

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#1168]
The RPC client currently only prints a generic error.
We should receive and print more useful errors instead.

This might require changes to: https://github.com/nimiq/jsonrpc

**Comment by cud4m** [comment]
Just a parameter with de data missing in the Display fmt  of RpcError. Although it can be improved more, here is fixed:
https://github.com/nimiq/jsonrpc/pull/3/commits
