### ISSUE TITLE
Prune epoch doesn't remove *all* micro blocks

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#1197]
`prune_epoch` is supposed to remove all micro blocks of an epoch.
To this end, it iterates over the block numbers and retrieves the blocks from the height index.

However, when there are forks, there could be duplicates at this height (see `get_blocks_at` for how to handle these).
Currently, we disregard such blocks.

Instead, we should iterate over all duplicates for a given height just as in the `get_blocks_at` function.

**Comment by jsdanielh** [comment]
I can take a look at this
