### ISSUE TITLE
RPC: Missing error codes

### ISSUE THREAD

**Issue by riptl** [nimiq/core-rs-albatross#125]
The RPC server doesn't return an error code on a lot of error responses.

This violates the JSON-RPC spec: https://www.jsonrpc.org/specification#error_object

>  code
A Number that indicates the error type that occurred.
This MUST be an integer.

**Comment by jgraef** [comment]
This is fixed with nimiq-jsonrpc. RPC method handlers always return `Result<_, E>` where `E` can be converted to an `RPCError`, which usually will be converted to an internal error. Anyway nimiq-jsonrpc, always responds with standard-compliant errors.
