### ISSUE TITLE
Review serialization

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#1293]
Currently, we rely on two different serialization libraries:
- our own `beserial`
- `serde`

We should review whether we can get rid of `beserial` in favour of `serde` in most places!

**Comment by sisou** [comment]
For use with WASM, `serde` would be better, as those structs can then be easily sent over to JS with the `serde-wasm-bindgen` crate.

**Comment by jsdanielh** [comment]
Addressed in #1656.
