### ISSUE TITLE
Optimize mempool synchronization

### ISSUE THREAD

**Issue by riptl** [nimiq/core-rs-albatross#133]
The current inventory vector-based mempool syncing is ineffective and fails to broadcast unconfirmed transactions to other validators in the narrow time-frame available for block production.
Under close-to-real network conditions (80ms latency, no packet loss) mempool pressure is very uneven across different validators: Some cannot "mine" transactions fast enough, others produce largely empty blocks.

I guess the inefficiencies are largely due to the round-trip needed with current inventory management. A push-based synchronization should allow for faster broadcasting of transactions.

**Comment by brunoffranca** [comment]
This is resolved with your update of the Inventory Manager, right?
@paberr
