### ISSUE TITLE
POS of the NIM

### ISSUE THREAD

**Issue by Stargazer77** [nimiq/core-rs-albatross#136]
Hello! I would like to express my opinion to the developers regarding the future transition to POS of the NIM. At the moment, the coin has a very good POW consensus algorithm, and there have been no special devices(asic) for it for all the time of mined (at least obvious ones), what I was very surprised, and the transition  to POS will most likely be the finish for the coin, at least for the benefit of the coin holders so precisely, even if the project itself will still try to do something and will work, despite loud statements. Personally, I will sell most of the coins that I have before  of the hard fork, and part sell immediately after it. You need to make at least a hybrid system leaving the old POW and POS. 
 !!! IF  BITCOIN  GO TO POS, HE WOULD DIE AND THIS EVERYONE IS EXCELLENT UNDERSTANDING !!! That’s why he will never do it.  I hope this will be useful for the project.

**Comment by riptl** [comment]
Hey @Stargazer77! The issue section is best suited for things like coding questions and bug reports.
Also check out the Nimiq Forum https://forum.nimiq.community/ or the community hub https://www.nimiq.com/community/
