### ISSUE TITLE
Implement `serde::{Serialize, Deserialize}` for primitives

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#14]
Implementing serde's `Serialize` and `Deserialize` would greatly reduce the amount of parsing, serializing code we need to write or have already written. E.g.:

 * The RPC server currently uses the `json!` macro to manually serialize some structs like `Block` and `Transaction`.
 * The config file loader implements `Deserialize` for structs that contain almost identical information to e.g. `NetworkId`.
 * It makes it easy to serialize to a lot of common formats.

**Comment by riptl** [comment]
@jgraef I'd like to fix this if you haven't started already

**Comment by jgraef** [comment]
While rewriting the RPC server I did make some structs `Serialize` and `Deserialize` behind a feature `serde-derive`. It only makes sense for smaller structs at the moment and a lot of structs can just be serialized to and from hex (see #197).
