### ISSUE TITLE
Support HTLC creation with SHA512 algorithm for JS-compatibility

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#140]
**The solution of this issue is a _requirement_ for a Nimiq 1.0 release of the rust node.**

Due to a probable oversight, HTLC creation is allowed in the Core-JS reference implementation with the SHA512 algorithm (enum `4`), which produces 64-byte outputs instead of the 32-byte outputs of Blake2b and SHA256. While redeeming SHA512 HTLCs is correctly prohibited in JS, its _creation_ is still very much allowed.

While knowing the limitation for redeeming a SHA512 HTLC, a community dev created [such an HTLC](https://test.nimiq.watch/#NQ66+0TSA+SBY1+VSJF+9RDA+QY2D+K55Q+YVYX+C2X9) in the testnet in block [#855673](https://test.nimiq.watch/#855673). Since all JS nodes accepted it, it is now part of the blockchain and changing it requires a hard-fork. The rust seed node that runs in the testnet (seed-4 I believe) did not accept it and is since stalled at that block.

For compatibility and to be able to sync the whole chain, the Core-RS implementation must also support the creation of such HTLCs, which it currently does not. The core-rs client stops syncing the testnet at the above mentioned block, due to an `Invalid creation data: invalid length` error when validating the transaction, leading to the block being rejected.

Initial work to enable SHA512 HTLCs has already been started by @paberr in the TransactionBuilder PR (https://github.com/nimiq/core-rs-albatross/pull/118: [htlc_contract.rs](https://github.com/nimiq/core-rs-albatross/pull/118/files#diff-72ba01438cf8dcc43d5f355ea9c8e201)).

However, @paberr was unaware of this issue, so the changes in that PR are not enough to accept such an HTLC yet, as the creation transaction is still validated against a static `hash_root` size of 32 bytes:
https://github.com/nimiq/core-rs-albatross/blob/ea7e43e8087bb224a027a7bec199269b2350ea25/primitives/transaction/src/account/htlc_contract.rs#L41-L44

An additional issue is that an HTLC account with a SHA512 64-byte hash root is not serialized correctly, which leads to a wrong accounts-hash even if the transaction is accepted. This wrong accounts-hash in turn leads to the rejection of the block again.

The account is not serialized correctly because the `AnyHash` typed array, which is used as a generic hash for the purposes of (de)serialization across the code base, is hard-coded to 32 byte size, prohibiting the dynamic serialization of 64 byte data:
https://github.com/nimiq/core-rs-albatross/blob/ea7e43e8087bb224a027a7bec199269b2350ea25/primitives/transaction/src/account/htlc_contract.rs#L148

As discussed with @paberr, a solution is to make `AnyHash` into a proper `struct` which knows its hash algorithm and can thus dynamically adjust its (de)serialization size. @paberr suggested to make `AnyHash` into an u8 vector struct (if I understood that correctly). This new struct would likely serialize already from the `hash_algorithm` indicator byte location, instead of only the hash bytes.

**Comment by brunoffranca** [comment]
No longer applies since this repo will be only for Nimiq 2.0. Anyway, the commit 44253aeddee2312a30b023fab481759f63bdad3f removes the Argon2d and SHA512 as options for HTLC contracts.
