### ISSUE TITLE
Duplicate RPC `get_batch_number` in `RPC server`

### ISSUE THREAD

**Issue by onmax** [nimiq/core-rs-albatross#1446]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [X] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## Issue

Duplicated `get_batch_number` in `RPC server`:
- [`blockchain::get_batch_number`](https://github.com/nimiq/core-rs-albatross/blob/albatross/rpc-server/src/dispatchers/blockchain.rs#L109)
- [`policy::get_batch_at`](https://github.com/nimiq/core-rs-albatross/blob/albatross/rpc-server/src/dispatchers/policy.rs#L47)

## Question or Feature Request

I don't know if there is a reason to have them duplicated or just an error.

**Comment by sisou** [comment]
As you can see at the linked methods, they have different signatures. The first does not accept an argument, the second does.

The first method returns the current epoch at the head of the chain. The second method can be used to calculate the batch number for any block number passed into it.

So the first method is a shortcut for doing two requests (get head block number and then policy::get_batch_at with that).
