### ISSUE TITLE
Transaction validity checks after restart

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#1473]
### General information
All our transactions have to be checked against already included transactions within the validity window.
This needs to be done to prevent replay attacks.

After restarting a validator (or regaining consensus) we might not have an up-to-date view on the validity window, though.
This depends on the sync mode.

We thus need to either wait with block production or preferably sync the transaction hashes from this window.

- [x] Only start validator when it has full validity window.
- [ ] Implement a way to sync the current validity window.

**Comment by ii-cruz** [comment]
This issue has been partially addressed in #1488. 
The next step would be to introduce a backwards syncing mechanism for the history tree.
