### ISSUE TITLE
Check that fork proofs are not included in more than one block

### ISSUE THREAD

**Issue by ii-cruz** [nimiq/core-rs-albatross#1481]
Currently, we check that a single block does not contain duplicate fork proofs.
However, it seems we do not check whether the same fork proof was part of another block in the reporting window.

Thus, fork proofs could be included more than once to re-park a validator despite an unparking transaction.

If we check this, we need to make sure a validator is able to enforce it (i.e., knows the already included fork proofs in that window).

**Comment by hrxi** [comment]
Fixed by #1882.
