### ISSUE TITLE
Add `retire_validator` method to the RPC interface

### ISSUE THREAD

**Issue by onmax** [nimiq/core-rs-albatross#1542]
# Description

With the addition of a new state called `retire` in the validators, it has become necessary to implement the corresponding method in the RPC server, interface, and client. These implementations were not considered during the initial implementation of the RPC interface. Therefore, they need to be added now.

**Comment by sisou** [comment]
Saying they were not considered is misleading. The `retired` state for validators was added only recently in #1451. That PR did not add the method for the new state to RPC.
