### ISSUE TITLE
The alpha testnet got stuck after validator drops and then rejoins

### ISSUE THREAD

**Issue by jeffesquivels** [nimiq/core-rs-albatross#161]
It was reported on our Discord that after a validator with a majority of the stake dropped off the network, the whole network stopped (which is to be expected) but then that same validator went online again but the network remained stuck for an unknown reason (this shouldn't happen, the validator should be able to re-join the network and participate in the voting process even if it was view changed already).

@paberr has this hypothesis about what could be happening:

`One thing I could imagine is that there’s a problem when rejoining the voting process for macro blocks. If the other nodes wait for your votes and don’t send around the information anymore (that’s the point I’m not sure of), your validator cannot get the necessary information to participate after rejoining the network.`

The full conversation where this is reported can be found [here](https://discord.com/channels/359979114062675969/360204777012854785/722041314992193587).

**Comment by viquezclaudio** [comment]
This scenario has been extensively tested with our new tendermint implementation. Closing it, since validators dropping and rejoining are fully supported now.
