### ISSUE TITLE
Transaction serialization changed

### ISSUE THREAD

**Issue by hrxi** [nimiq/core-rs-albatross#1698]
Due to the serialization changes in #1656, replacing our custom `beserial` with [`postcard`](https://postcard.jamesmunns.com/) via `serde`, the serialization of transactions changed. This is a problem because there are third-party tools (and also our own keyguard!) that hand-craft/interpret raw transactions.

**The question is whether we want to revert to the old serialization or go ahead and change the serialization, possible optimizing it for size a little bit more.**

Change analysis of @sisou:
```
// Serialized unstake tx from core-rs-albatross
01 // tx type (extended)
00 // data length 0
0000000000000000000000000000000000000001 // sender
03 // sender type
8314ae0f9e42e6d872c0bc07b09e2a278b1dfbae // recipient
00 // recipient type
0000000000000001 // value
0000000000000000 // fee
00020d0e // validity start height
05 // network ID
00 // flags
64 // proof length?
01 // proof type (unstaking)
b3b600099dcf014b9689880aa1275603cc6f59056842049f3009921e32a07471 // signer pubkey
000000 // merkle path
9e656355265782fb5fb0f40ccb5d051a7b9cb297ad55c7a20ef8d8ce662bc7a23b4f4f336aa51ea8170cbb8136d7d64d43bed01cde45b9f937eb5ba365556a0c // signature

// Serialized unstake tx from Keyguard using core-js
01
0000 // data length
0000000000000000000000000000000000000001
03
6bf09f633d2204f38e243d8a5ebeb72391075a7e
00
000000001dffbfa0
0000000000000000
00020fce
05
00
0062 // proof length?
01
39c3a6af6b86f4f9e228710181ca7cde8b95deda126a26494ee2b156a1aa1fee
00 // merkle path
6b6946c45bc9826be5ce50de9b1e15c3335ce2d0be8bf21769f225e399ecf45fd620455062181c021ba6eeb12f26619bd4a4ccd28dbfdf087321b3eee66ed502 // signature
```

Data length/proof length is now a postcard variable-length integer and the serialization of the empty merkle path also changed.

**Comment by sisou** [comment]
The serialization of merkle paths is implemented here:

https://github.com/nimiq/core-rs-albatross/blob/e4d336b32cbb31448f9ec1b9fc85148dea3d493e/utils/src/merkle/mod.rs#L166-L172

This always assigns it 3 fields (line 171), no matter how many nodes the path has. To recreate previous behavior of an empty merkle path serializing to only one empty byte, the serializer and deserializer needs to be adapted.

**Comment by hrxi** [comment]
Seems like it was no problem to change the serialization.
