### ISSUE TITLE
Integrate and test Macro Block Sync

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#18]
Once #16 and @jgraef's new config builder is merged, the Macro Block Sync protocol needs to be integrated and tested.

**Comment by jgraef** [comment]
TODO: Box either `SyncProtocol` or `ConsensusProtocol` and implement interface on it.Then we can instantiate the correct one in `nimiq_lib2::client`.

**Comment by styppo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate MacroBlock sync](https://trello.com/c/v5eWfUgt/2-integrate-macroblock-sync)
