### ISSUE TITLE
inactivityFlag is in the future

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#1860]
For an unknown reason my node received an `inactivityFlag` number that is a few thousand blocks ahead

![image](https://github.com/nimiq/core-rs-albatross/assets/8634939/9f343331-de66-4de6-b10e-809cf581201b)

![image](https://github.com/nimiq/core-rs-albatross/assets/8634939/f7220033-fc06-4911-bc6e-e183cc2532ee)

**Comment by sisou** [comment]
That is on purpose and was changed with the last restart. It is the block number of the _next_ election block. It shows that the validator is only really inactive in the next epoch.

**Comment by sisou** [comment]
See #1795 for the change.
