### ISSUE TITLE
Invalid Proof in WebClient Transaction::Sign

### ISSUE THREAD

**Issue by faberto** [nimiq/core-rs-albatross#1879]
Signing InStaking transactions is broken in the webclient.

## Problem
Instead of returning the transaction the proof is set in place.
But not on both transactions

## Reproduce
Use the webclient to create a transaction using  
`Nimiq.TransactionBuilder.newCreateValidator`
then use `sign` on this transaction and try to   
send it using the `sendTransaction` of the client

## Change that introduced it
https://github.com/nimiq/core-rs-albatross/pull/1755

## The Code
https://github.com/nimiq/core-rs-albatross/blob/albatross/web-client/src/transaction.rs#L185-L199

**Comment by sisou** [comment]
~I think it still works correctly for staking transactions, so it's not completely broken.~

It may not work correctly for ~validator~ in-staking tx, as those require an additional signature in the `data` field.

So in addition to setting the proof on the original tx, the method might need to copy the `data` field, too? 

https://github.com/nimiq/core-rs-albatross/blob/8f2ea1f5a0df3da48d65e9e9283999fbf414b4bc/web-client/src/transaction.rs#L199

Edit: yes, I confirm this bug

**Comment by sisou** [comment]
Originally I was convinced that it's only a problem for validator txs, as staking still works correctly in the wallet.

But then I found that I never updated the Keyguard to a client version after 0.13.0, and #1755 went into 0.13.1 only. So the Keyguard still uses the old duplication behavior, creating valid transactions.

We should add a test to verify that the web-client produces valid transactions.
