### ISSUE TITLE
Full node not syncing 

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#1880]
In the private testnet, there is one node that starts syncing and logging:
`Peer is sufficiently close for a live sync instead of macro sync. our_head=3693599 peer_head=3693660 peer_id=12D3KooWF9v6ySqGMXLdRVF52dTMjtJHfLPqWwimPFMtAEgrgDzt`

However, after several minutes, there is an error showing  in the live queue:
`Queue not ready to receive data: no available capacity`

With no progress being shown in terms of syncing, the node remains without any consensus.

Full validator log:
[privtestnet_validator3.log](https://github.com/nimiq/core-rs-albatross/files/12753459/privtestnet_validator3.log)

**Comment by Eligioo** [comment]
Maybe #1704 is related to this issue where the full node is also not able to apply the election block.
