### ISSUE TITLE
Convoluted rogue-key attack on BLS

### ISSUE THREAD

**Issue by brunoffranca** [nimiq/core-rs-albatross#192]
Quoting from @paberr :

> According to this paper (http://www.sysnet.ucsd.edu/cryptosec/miscpapers/pkreg-ec07.pdf), our current proofs of knowledge are insecure as we use the same hash function for producing the proof and any other signature. The attack requires to be able to get a signature of one’s own public key by another signer, which seems a bit unpractical, but certainly possible in the RO model.

It is a very, very (very) unlikely attack but we can easily fix it. Simply create two new functions on the bls crate, `create_pop` and `verify_pop`. The first one takes a keypair as input and outputs a PoP (proof-of-possession), the second one takes as input a keypair and a PoP and outputs a boolean stating if the PoP is valid.

The trick is that the PoP will use the Blake2s hash function (like a normal signature) but with the personalization field set to a unique value (the specific value doesn't matter). Then this attack will not be possible.

**Comment by jgraef** [comment]
This was the motivation behind making the `AggregateProof` generic over a `Message` type that has a constant that is used while hashing: https://github.com/nimiq/core-rs-albatross/blob/b699ffa888a0ca1eda3973899bef9b87cb79cfc2/primitives/block-albatross/src/signed.rs#L78

Some maybe we should make this more general over non-aggregated signatures as well.

PS: The other advantage of a type-paramter on the signature is that the Rust type system doesn't allow you mixing unrelated signatures.

**Comment by brunoffranca** [comment]
This solves it then!
