### ISSUE TITLE
Rename `get_active_validators` to `get_assigned_validators` or `get_current_epoch_validators`

### ISSUE THREAD

**Issue by onmax** [nimiq/core-rs-albatross#1930]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [X] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

There is a method in the RPC called [`get_active_validator`](https://github.com/nimiq/core-rs-albatross/blob/1d65be20320a9ef2ce58bc898c4c1e59323bac2f/rpc-server/src/dispatchers/blockchain.rs#L506-L530). This method currently retrieves a list of validators that are producing blocks in the current epoch.

However, it appears that this method does NOT includes validators that are not actively producing blocks in the current epoch, but are still considered to be active on the network. This inclusion suggests that the term `get_active_validators` may be slightly misleading or not entirely accurate as currently used.

**Comment by sisou** [comment]
Or the method returns the wrong result.

**Comment by onmax** [comment]
Or I was just wrong. I misunderstodd something.

The method basically reads the value of active validator from the staking contract


```rust
pub struct StakingContract {
    // The total amount of coins staked (also includes validators deposits).
    pub balance: Coin,
    // The list of active validators addresses (i.e. are eligible to receive slots) and their
    // corresponding balances.
    pub active_validators: BTreeMap<Address, Coin>,
    // The punished slots for the current and previous batches.
    pub punished_slots: PunishedSlots,
}
```

[Source code](https://github.com/nimiq/core-rs-albatross/blob/albatross/primitives/account/src/account/staking_contract/mod.rs#L61)
