### ISSUE TITLE
Implement `FromHex` and `ToHex` consistently

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#197]
We use the `hex` crate for many data-structures. It would be neat to have `FromHex` and `ToHex` consistently implemented for these types. This would e.g. make it easier to have a serde helper function that can serialize/deserialize anything to its hex representation (this is used a lot in the RPC server and some other places).

**Comment by Eligioo** [comment]
@jgraef is this issue still relevant? If so, can you give some more details. I would like to contribute.

**Comment by jgraef** [comment]
I don't think this is possible with how `ToHex` and `FromHex` are defined. We do have a lot of methods to turn objects into a hex-string. Sometimes this is used for `Display`, `serde::Serialize`. So maybe we could have our own traits for that. But this is very low priority for us right now.
