### ISSUE TITLE
History nodes do not consider full nodes for any consensus related operations

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2024]
Currently, history nodes do not add full nodes to their consensus-syncing process.
This logic can be observed [here](https://github.com/nimiq/core-rs-albatross/blob/albatross/consensus/src/sync/history/sync_stream.rs#L35-L41).

This is somewhat expected because full nodes do not provide the full transaction history (represented by the _HISTORY_ services flag), and thus, they cannot be used by History Nodes to do history sync.

However, this also affects block announcements, because the blocks that are emitted by full nodes are not being taken into consideration by history nodes and this is problematic.

It has been observed in several instances of the Testnet and the CI, (if there is a majority of history nodes), that Full nodes produce blocks, but history nodes are unaware of those blocks, causing the full node to erroneously be skip-block and penalized. Eventually, the full node notices a superior chain and needs to reactivate.

**Comment by styppo** [comment]
Fixed in e7a0319
