### ISSUE TITLE
Peer Filtering

### ISSUE THREAD

**Issue by faberto** [nimiq/core-rs-albatross#2052]
Especially for the WebClient there needs to be an option do forbid connections to insecure sockets.  
Otherwise the browser will flag the page as insecure.

Suggested filter rules:
- disable Insecure: true/false    ->disables ws://
- disable local IPs: true/false    ->disables all non public IPS

**Comment by hrxi** [comment]
> * disable local IPs: true/false    ->disables all non public IPS

It seems clients should generally not connect to local IP addresses, I think it shouldn't be a config options.

**Comment by sisou** [comment]
Not sure secure connections even work with IPs, as opposed to domain names. So in a browser IP-only connections should be prevented.

**Comment by faberto** [comment]
> > * disable local IPs: true/false    ->disables all non public IPS
> 
> It seems clients should generally not connect to local IP addresses, I think it shouldn't be a config options.

If you run multiple nodes in a local network you would like the to talk to eachother locally.

**Comment by hrxi** [comment]
> Not sure secure connections even work with IPs, as opposed to domain names. So in a browser IP-only connections should be prevented.

It can work: https://1.1.1.1/.

It's rare though.
