### ISSUE TITLE
Update zexe dependencies

### ISSUE THREAD

**Issue by brunoffranca** [nimiq/core-rs-albatross#206]
Zexe is moving to arkworks (https://github.com/scipr-lab/zexe/pull/320). We need to update the bls and nano-sync crates.

**Comment by Pratyush** [comment]
For the time being I think you can just pin to the latest tag/commit for zexe, so that your project keeps compiling.

**Comment by brunoffranca** [comment]
Thanks, @Pratyush. We already do that. The crates I referred to use nimiq/zexe, which is our fork of Zexe.

**Comment by Pratyush** [comment]
Ahh, sounds good!
