### ISSUE TITLE
Validator inactive in the future

### ISSUE THREAD

**Issue by redmaner** [nimiq/core-rs-albatross#2084]
### General information

- Library version(s): 0.18.0
- Reproducible in the testnet? (Yes/No):  yes
- Related issues:

## Bug report
We are running an archival node to run our validator on for the AceStaking pool. Validator has address `NQ65 DHN8 4BSR 5YSX FC3V BB5J GKM2 GB2L H17C`  on testnet. This validator is consistently getting inactivated. We noticed that when retrieving the validator using `getValidatorByAddress`  RPC method the `inactivityFlag` for the validator is set in the future. At the time of writing the validator's inactivityFlag is set to block `12236050`   while the head of the chain is at `12236050`  this is a deficit of around `40000` blocks in the future. 

The node itself in the logs shows the right consensus height.  
```
2023-12-30T15:05:39.563186645Z INFO  nimiq_client         | Consensus: established - Head: [#12194650](tg://search_hashtag?hashtag=12194650):MA:03df933da5 - Peers: 19 consensus_established=true block_number=12194650 num_peers=19
```

Reactivating the the validator doesn't work and the inactivityFlag stays at block `12236050` .

**Is this a bug, or is this intended?**

**Comment by sisou** [comment]
IIRC the flag is set to the next election block. From there, the inactive release starts counting, which I think is one epoch, until it can be retired and deleted.

The reactivation failing is a different issue. Do you have more details about a reactivation tx you are sending?

**Comment by redmaner** [comment]
I assume you can't reactivate a validator before the inactivityFlag block number has passed? So it can only be activated in this case after block 12236050?

**Comment by sisou** [comment]
No, that's not checked then. Can you share a tx hash of a reactivation tx you sent? Or are they sent from the validator address?

**Comment by redmaner** [comment]
They are sent from the validator address

**Comment by redmaner** [comment]
The txs work in the sense that they get mined / validated. But the validator stays inactive, but as I mentioned I assumed reactivation would only take affect after the inactivityFlag height

**Comment by sisou** [comment]
It seems you figured it out today. I see you sent many reactivation transactions that had `executionResult: false` earlier today. Then your validator started producing blocks, but after each batch was deactivated and activated again for 26 minutes. After that it stays active. Do you know what caused the problem?

**Comment by sisou** [comment]
I just noticed that being jailed prevents reactivation. Do you know if your validator was jailed when you tried sending the unsuccessful transactions?

**Comment by sisou** [comment]
As a definitive answer to your initial question: here is the code comment saying that `inactive_from` is set as the next election block:
https://github.com/nimiq/core-rs-albatross/blob/6f6d00bb66596735696918442b42ff244b4731b8/primitives/account/src/account/staking_contract/validator.rs#L76-L80

Here's the details about being jailed:
https://github.com/nimiq/core-rs-albatross/blob/6f6d00bb66596735696918442b42ff244b4731b8/primitives/account/src/account/staking_contract/validator.rs#L81-L85

The jail period is 8 epochs worth of blocks.

Both fields are sent in the RPC response to `getValidatorByAddress` if they are not empty.

**Comment by redmaner** [comment]
Thanks Soeren. No I don't know what happened exactly around that time. But I'm still a bit confused though. So two follow up questions:

1. The inactivityFlag for our validator is gone before 12236050 passed but that didn't happen immediately after the first tx that returned `exectionResult:true` therefore more transactions were sent. This is something we'll have to optimize on our end, but what are the definitive parameters to use to tell if reactivation is successful when a reactivation tx is ok but the inactivityFlag is still there? Is there some time to take into account before this takes into effect.
2. What is jail time exactly? This the first time I hear about it, and what should we do if anything when a validator is in this state?

**Comment by sisou** [comment]
1. That tx you describe should have had the desired effect. Make sure you don't get cached RPC responses, maybe wait a block or two to query the validator again. You might run into race conditions when another node mines the tx and your node didn't apply the block yet, when you query immediately after sending. But execution result true means it got applied.
2. Jailing happens for serious offenses, which usually only happen when you run two nodes with the same validate keys, or are on purpose trying to split the network. More details will be in the upcoming dev center. When jailed, you cannot change the state of your validator at all, neither can your stakers. Jailing applies for 8 epochs worth of blocks from the `jailed_from` block.

**Comment by redmaner** [comment]
Thanks for all the info. I'll have to revisit this when we get in an inactive state again
