### ISSUE TITLE
Error while compiling: cannot find attribute `stream` in this scope

### ISSUE THREAD

**Issue by kryptokraken** [nimiq/core-rs-albatross#217]
### General information

- Library version(s): Last version
- Devices/Simulators/Machine affected: **Ubuntu 20.10 on Raspberry Pi 4 x64**

#### Expected behavior
Successful compile

#### Actual behavior
**Compiled failed**

#### Steps to reproduce

Clone project default branch and
`~/core-rs-albatross# cargo +nightly install --path client/`

#### Crash log? Screenshots? Videos? Sample project?
```
error: cannot find attribute `stream` in this scope
  --> rpc-interface/src/blockchain.rs:40:7
   |
40 |     #[stream]
   |       ^^^^^^

error: aborting due to previous error

error: could not compile `nimiq-rpc-interface`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nimiq-client v0.1.0 (/root/core-rs-albatross/client)`, intermediate artifacts can be found at `/root/core-rs-albatross/target`

Caused by:
  build failed
```

## Question or Feature Request

**Comment by Eligioo** [comment]
Try enabling the `proxy` feature for the `nimiq-rpc-interface` crate. For a project I included the `nimiq-rpc-interface` crate as an external dependency like this:
```rust
nimiq-rpc-interface = { git = "https://github.com/nimiq/core-rs-albatross.git", branch = "albatross", features = ["proxy"]}
```
Adding this feature solved the problem where `rustc` couldn't find the `stream` attribute.

Since you are using the cli, try appending `--features "proxy"`:
```cargo +nightly install --path client/ --features "proxy"```
