### ISSUE TITLE
[RPC] - U16 Limit for "getTransactionHashesByAddress" prevents all tx to be fetched

### ISSUE THREAD

**Issue by maestroi** [nimiq/core-rs-albatross#2247]
## New issue checklist

- [X] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [X] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 0.20.0 >
- Browser version(s): - 
- Devices/Simulators/Machine affected: -
- Reproducible in the testnet? (Yes/No):  Yes
- Related issues: -

#### Expected behavior

{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransactionHashesByAddress",
    "params": [
        "NQ65 DHN8 4BSR 5YSX FC3V BB5J GKM2 GB2L H17C",
        90000
    ]
}

To fetch all 90k transactions 

#### Actual behavior

{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params",
        "data": "Expected an object for the request parameters."
    },
    "id": 1
}

if the int is higher than 65535 there is invalid parameter error 

#### Steps to reproduce

--- CORRECT REQUEST
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransactionHashesByAddress",
    "params": [
        "NQ65 DHN8 4BSR 5YSX FC3V BB5J GKM2 GB2L H17C",
        65535
    ]
}

--- INCORRECT
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransactionHashesByAddress",
    "params": [
        "NQ65 DHN8 4BSR 5YSX FC3V BB5J GKM2 GB2L H17C",
        65536
    ]
}

#### Crash log? Screenshots? Videos? Sample project?

NO

## Question or Feature Request

I only checked this specific RPC call but there could be more

**Comment by ii-cruz** [comment]
iirc this is the desired behavior since these requests are expensive for the node.

**Comment by maestroi** [comment]
@ii-cruz that sounds nice but how do we know about old transactions by account

**Comment by sisou** [comment]
My suggestion was to change this in your own fork, but I see how that's inconvenient, as it preclude you from just using the official docker container or build.

How about adding a config option to the RPC section that enables more advanced features like this, with the appropriate warnings? I don't know if a config switch can change an argument, or if it would just enable and disable between two almost identical methods.

**Comment by maestroi** [comment]
An config option would be nice, or a u32 container build

**Comment by ii-cruz** [comment]
We could bundle all of the more expensive rpc options into one config option for example. There are more instances of this iirc.

This will likely be a very low priority to look at since we are still investigating what to do with these indexes that are slowing down the history sync #1998.

**Comment by paberr** [comment]
Related to #2733 and #2697
