### ISSUE TITLE
Feature request - expose an interface to retrieve all affected addresses from a transaction

### ISSUE THREAD

**Issue by redmaner** [nimiq/core-rs-albatross#2252]
Current transactions returned over RPC include the `from` and `to` fields but these fields do not always cover all affected addresses in the transaction.

For example:
* given pool X 
* having delegated staker A 
* pool X adds stake to staker A 
* the transaction `from` field is set to pool X and the recipient is set to the staking contract. The address of staker A has to be parsed from `recipientData`

This issue requests either of two things:
* include the `staker_address` in the transaction, so we always know which staker is affected by a staking contract transaction and / or 
* expose an RPC method to retrieve the affected addresses for a transaction. Apparently a transaction struct already has a function to retrieve affected addresses which may be something that can be exposed over RPC so other languages don't have to manually parse convoluted fields to retrieve the required information.

**Comment by sisou** [comment]
Hmm... seems I was mistaken when I said there is already an internal mechanism to get affected addresses for a transaction. The history store in fact only indexes by sender and recipient :(

https://github.com/nimiq/core-rs-albatross/blob/fe7c294f0daaa46318ab92cb4324a02a6a31f6d1/blockchain/src/history/history_store.rs#L955-L976

Probably what I remember was just an idea, instead of implemented.

**Comment by sisou** [comment]
Here is what I remembered: the `Log` struct has this method!
https://github.com/nimiq/core-rs-albatross/blob/89a8b67017d4af82b6be741531b1ec9e252b3506/primitives/account/src/logs.rs#L222

**Comment by paberr** [comment]
It will be difficult to make this accessible from the transaction itself.
However, that's what the `Log` mechanism was designed for: to get more meaningful "events" related to specific addresses.

@redmaner: Does the Log mechanism solve your problem?

**Comment by redmaner** [comment]
Why is this difficult to make accessible from the transaction itself while the data is encoded in ` recipient_data`  and `sender_data`  just in an non human readable format? Having RPC calls to decode that into JSON would already be helpful

**Comment by joeleol** [comment]
+1 on this feature request. The stakers will see their wallet balance miraculously increase with each payout from my pool, therefore payouts cannot be seen/tracked in the web-wallet. I think a use-case for this request could be for annual tax declarations (in some countries people have to declare their staking income).  I will of course have a record of these transactions in my db of pool payouts, but I plan to truncate this several times per year (depending on size).

**Comment by redmaner** [comment]
@sisou you're a legend!
