### ISSUE TITLE
RPC - Bugs, missing methods, inconsistencies

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#229]
This is a collection issue for bugs, missing methods and inconsistencies I found when testing the RPC server:

- [x] Method `blockByNumber` does not accept a `number` as the first argument, only stringified numbers
- [x] Methods `blockByNumber` and `blockByHash` require a second argument (`include transactions: bool`) - I think this should be optional and default to `false`
- [x] Naming inconsistency: `blockByNumber/Hash` vs `getTransactionByHash` - make `get` prefix consistent (either with or without)
- [x] Panic when requesting `getAccount` with the staking contract address: `thread 'tokio-runtime-worker' panicked at 'Failed to serialize return value: Error("the enum variant Account::Staking cannot be serialized", line: 0, column: 0)': /usr/local/cargo/git/checkouts/jsonrpc-9fb05bf7e43ac4a6/1d17aa2/nimiq-jsonrpc-server/src/lib.rs:513`
- [x] Missing method to request current `consensus` state
- [x] Missing method to request current `peerCount`, `peerList`, `peerState <peerId>`
- [x] Missing method to set `log` level
- [x] Missing method to set `constant`s
- [x] Missing method to retrieve `validatorKey`, `validatorId`
- [x] Missing method to retrieve `minFeePerByte`
- [x] Missing method to `unsubscribe`from subscriptions
- [x] `mempool` methods throw "not implemented" error
- [x] Properties of returned objects mix `camelCase` and `snake_case` within the same object (example: `Block { blockNumber, extra_data, parentHash, parent_election_hash }`
- [x] Accounts from `getAccount` are returned with the account type as a property instead of a value: `{"Basic":{"balance":168157712802}}` - the type should rather be the value of a `type` property
- [x] Interacting with a locked wallet panics instead of returning the error correctly: `thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: UnlockedWalletNotFound(Address("8314ae0f9e42e6d872c0bc07b09e2a278b1dfbae"))': rpc-server/src/dispatchers/consensus.rs:124`
- [x] `getTransactionByHash`, `getTransactionReceipt` not implemented
- [x] All transaction-creation/sending methods require a last `validityStartHeight` argument. I think this should be optional and default to the current head height
- [x] `validityStartHeight` argument for transaction creation/sending methods does not accept numbers, only stringified numbers
- [x] Closing the websocket after subscribing to headers does not close the stream on the server and leads to continuous errors: `ERROR nimiq_jsonrpc_server | Queue error: channel closed`
- [x] Creating a validator reactivation transactions fails (on `soeren/rpc` branch)

**Comment by jgraef** [comment]
I'll work on this. Most of it seems easy to fix. (Sorry for accidentally closing it :D)

the blockByNumber only accepting strings is certainly a bug, but it stems from the fact that core-js's `blockByNumber` either accepts the block number or `"latest"`. I'd suggest splitting this:

- `blockByNumber(block_number: u32)`
- `blockLatest()`

I don't like the naming scheme too much. I'd rather call the methods `getBlockByNumber` and `getLatestBlock` and so on. Any opinions?

**Comment by jgraef** [comment]
Yes, the argument `include_transactions` should be optional, but that's not supported by nimiq-jsonrpc right now. I opened a separate issue for that: https://github.com/nimiq/jsonrpc/issues/1

**Comment by brunoffranca** [comment]
@jgraef For the `getTransactionByHash` you need a Blockchain method that doesn't yet exist, but I'm working on that. I'll ping you when that's merged.

**Comment by jgraef** [comment]
Here's the branch where I'm working on this: https://github.com/nimiq/core-rs-albatross/tree/janosch/rpc

Since this is needed for going further with the testnet, this is high priority, right?

**Comment by jgraef** [comment]
Unsubscribing to a stream is another missing feature in nimiq-jsonrpc: https://github.com/nimiq/jsonrpc/issues/2

**Comment by brunoffranca** [comment]
@jgraef Done. It's here 51a184fbe41dd38fc9fa77c6a9c9d9dc7af346fa.

**Comment by vlvrd** [comment]
The unsubscribe functionality is enabled now: https://github.com/nimiq/jsonrpc/commit/41d26fc1aa4fffde2ded7d4c187c9d693a588aed

The stream is also closed in the server when the websocket is closed, so *that* is also fixed but this uncovers a bug in the observer when following blocks since we keep sending blocks to a receiver that no longer exists.

**Comment by sisou** [comment]
Closing PR was reverted.

**Comment by brunoffranca** [comment]
Re-merged.
