### ISSUE TITLE
Migration: Migrate existing history proactively 

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2355]
Do not wait until the activation window to start migrating the history: the majority of it is not going to change so we can eagerly migrate the history if the tool is started before the activation window.

**Comment by sisou** [comment]
Does the tool migrate all history, aka all transactions? I thought only the current accounts-state.

**Comment by jsdanielh** [comment]
> Does the tool migrate all history, aka all transactions? I thought only the current accounts-state.

It does, that's how the genesis history root is obtained.
