### ISSUE TITLE
Migration: Create a command to dump the stake allocation 

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2387]
Create a command to dump the stake allocation once the pre-stake window is finished.

**Comment by joeleol** [comment]
Could I please request to add options, such as: for a specific validator and different file export formats (e.g. CSV), this would be helpful for validators (such as me) to import genesis data into databases as a first snapshot.

**Comment by Eligioo** [comment]
@joeleol filtering the stake allocation for a specific validator is a good suggestion and part of PR #2395. Regarding support for specific file formats as output it a bit to subjective as it depends on your needs. Transforming the output of the `list-stakers` command into your desired file format shouldn't be big effort now.
