### ISSUE TITLE
Migration: Validator change in pre-staking window not detected

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#2399]
This address https://test.nimiq.watch/#NQ95+FHVN+JAN4+8LKT+LCE2+LC3T+P861+NK5M+HVGS delegated 2.8 million NIM to `NQ65 ... H17C` in block `3027744`. Then it sent a 1 NIM transaction 3 minutes later in block `3027747` with data to delegate to `NQ26 ... XVNY`. That should have changed the delegation to the later validator.

However, in the genesis file this staker is delegating to `NQ65 ... H17C`, which I think is incorrect.

**Comment by jsdanielh** [comment]
Issue seems to be that we are doing the minimum stake check for every transaction individually and not for the sum of all of the transactions that come from the sender and that also meet the pre-staking requirements
