### ISSUE TITLE
Rpc call doesn't work for Reward transaction

### ISSUE THREAD

**Issue by DovAzencot** [nimiq/core-rs-albatross#2408]
getTransactionByHash RPC call doesn't work on Reward transaction, for example for the reward tx
{
                "type": "reward",
                "blockNumber": 3119250,
                "blockTime": 1714164925985,
                "validatorAddress": "NQ57 2F6C X3GB Y9B7 04U5 2BVA 4BVC M2T0 ELRL",
                "target": "NQ57 2F6C X3GB Y9B7 04U5 2BVA 4BVC M2T0 ELRL",
                "value": 7077840,
                "hash": "22333611d8908e568da2b25f9ffe88272b64dcbdd02baa2d0256676e744862f5"
            },

getTransactionByHash using the above hash yield no result.

**Comment by hrxi** [comment]
Is this fixed by #2470 maybe?

**Comment by sisou** [comment]
@DovAzencot can you share how you got that object in your issue with the hash that doesn't work?

**Comment by Eligioo** [comment]
@sisou it's the getInherentsByBatchNumber or getInherentsByBlockNumber RPC methods.

**Comment by sisou** [comment]
Thanks @Eligioo!

@hrxi I just tried it, and the inherents returned by those methods still have invalid hashes.

**Comment by hrxi** [comment]
Thanks for testing!
