### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by maestroi** [nimiq/core-rs-albatross#242]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [ ] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

I first build everything on wrong branch (master) afther that i deleted the repo and cloned again.
Tried to build and it failed see crashlog.

Docker version 20.10.5, build 55c4c88

docker-compose version 1.28.6, build 5db8d86f

Ubuntu 20.04 fully updated

#### Expected behavior

Build albatross nodes

#### Actual behavior

Panics at build and stops

#### Steps to reproduce

docker buildx build -f build_ubuntu.Dockerfile . -t core --progress=plain

#### Crash log? Screenshots? Videos? Sample project?

https://pastebin.com/yUbEZKZx

## Question or Feature Request

> ...

**Comment by frvfrvr** [comment]
Hi Maestro, I also have the same issue as you, only the difference is error code 100 for me.

Docker version 20.10.5, build 55c4c88
docker-compose version 1.28.5, build unknown
Raspbian GNU/Linux 10 (buster) version 10
Raspberry Pi 4B 8GB model

Crash log: https://pastebin.com/rMaFXqh2
This crash log is 3rd time I did the same command (_docker buildx build -f build_ubuntu.Dockerfile . -t core --progress=plain_)

Adding _sudo_ also goes to same end.

Update: Another try with "_git checkout lab-test_" for lab testing yet reached the same conclusion.

**Comment by maestroi** [comment]
got mine fixed be reinstalling
