### ISSUE TITLE
`proposal_buffer::it_resolves_blocks` test failed

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#2429]
In [run](https://github.com/nimiq/core-rs-albatross/actions/runs/8908806008/job/24465068833?pr=2417) for an unrelated PR it has been observed that the `proposal_buffer::it_resolves_blocks` test failed once.

[job-logs.log](https://github.com/nimiq/core-rs-albatross/files/15200749/job-logs.log)

**Comment by nibhar** [comment]
Looking at the run it seems like the block actually does get resolved. The block in question is the one with hash `f9a32339e2d4f35d4a7bf4458a00c39393f88436c8c64f23991ae0b3f7ef70fa`, which is also pushed and accepted just before execution stops and the test fails with the elapsed timeout. Maybe that timeout is poorly chosen, as it really is there to detect divergence more so than a speedy reply. 
Is there any other contributing factor that would make execution here slower than usual? 400ms is still quite a bit of time.

**Comment by Eligioo** [comment]
I've looked more into this and compared the elapsed times for this test with other CI runs which takes around 6 seconds to complete. My feeling at the moment says that while the failed test was running, the CI infrastructure couldn't serve the resources in order to compute the proposal within the set deadline timeout of 400 ms. As it is very likely that runners are running on a [shared infrastructure](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners) among others. Running this on my host consecutively resulted in sub-second passes. I have no reason to believe something is broken at the moment and consider this a one-time occurrence.
