### ISSUE TITLE
RPC get_block_by_hash unable to get micro blocks

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#244]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): 
- Related issues:

## Bug report
Only for micro blocks I'm unable to get the block when using `get_block_by_hash`. Macro (both election and checkpoint) blocks work.

#### Expected behavior

Fetch the block from the RPC server by block hash.

#### Actual behavior

```JsonRpc(Json(Error("invalid type: string \"\", expected a borrowed string", line: 0, column: 0)))```

#### Steps to reproduce

```rust
async fn head_subscribe(mut self) -> () {
        let mut stream = self.blockchain.head_subscribe().await.unwrap();
        while let Some(hash) = stream.next().await {
            let block = self.blockchain.get_block_by_hash(hash, false).await;
            match block {
                Ok(block) => {
                    println!("{:?}", block.hash);
                },
                Err(e) => {
                    println!("{:?}", e);
                }
            }
        }
    }
```

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by redmaner** [comment]
Maybe this is already fixed in the meantime, but I don't have this issue. I can retrieve all blocks without any problem. Both micro blocks, and election and checkpoint macro blocks.
