### ISSUE TITLE
Investigate increasing memory usage of the `web-client` in browsers

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#2443]
## New issue
I created this issue as a reference for the ever-growing memory usage of the `web-client` in browsers. I have only verified that in Chrome this issue is showing but I think it's safe to say that for other browsers this happens too.

After having the Nimiq Wallet tab open for an hour, 4.9 GB of memory usage was observed on my system by simply have it open and let it do nothing.

<img width="962" alt="Screenshot 2024-05-08 at 14 33 16" src="https://github.com/nimiq/core-rs-albatross/assets/8634939/fc6e98f1-3d9d-41fb-9634-820dba2ce4bd">

**Comment by sisou** [comment]
I remember you finding that tracing consumes loads of memory in NodeJS. Maybe a similar thing happens here? 
Or do the log messages maybe make up the bulk of the memory? What happens when you reduce the log level to `warn` or even `error`. Does it reduce memory consumption?

**Comment by Eligioo** [comment]
Yes I've been profiling a bit now and at first glance, the PerformanceMarks and PerformanceMeasures seem to pile up indefinitely in the worker. Not sure yet if this is the culprit but at least something that needs fixing regardless.
