### ISSUE TITLE
Missing OpenRPC specficiation in v0.21.1

### ISSUE THREAD

**Issue by onmax** [nimiq/core-rs-albatross#2448]
According to the new [Testnet 0.21.1](https://github.com/nimiq/core-rs-albatross/releases/tag/v0.21.1), the OpenRPC specification is missing from the assets.

This file is important to generate the documentation for the developer center. 

For now I will hardcode the version to [Testnet 0.21.0](https://github.com/nimiq/core-rs-albatross/releases/tag/v0.21.0)

**Comment by sisou** [comment]
The PR is not yet merged: #2417. The previous release file was probably added manually, or through testing of the workflow.

**Comment by Eligioo** [comment]
@onmax the document is now added to the latest release.
