### ISSUE TITLE
Set default parameters for argon2 for otp

### ISSUE THREAD

**Issue by hrxi** [nimiq/core-rs-albatross#2472]
https://github.com/nimiq/core-rs-albatross/blob/397c7fe0977867f93bf87a3199b1fbcdcc089d9d/utils/src/otp.rs#L340-L343

**Comment by hrxi** [comment]
Probably also:

https://github.com/nimiq/core-rs-albatross/blob/d1e17ef853eedd58650b9f164af16eedb0dc35cc/hash/src/argon2kdf.rs#L4-L5

**Comment by Eligioo** [comment]
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id
