### ISSUE TITLE
Migration: Migrate the PoW Testnet to a then persistent PoS Testnet.

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#2501]
The current PoW Testnet should eventually be migrated to a PoS Testnet which is then kept around. That new PoS Testnet would replace the current PoS Testnet. 
The migration process should resemble as closely as possible the eventual Mainnet migration process. Also provide adequate infrastructure to maintain this Testnet in the long run. 
This infrastructure should also provide means for community developers to receive sufficient funding to test their applications.

**Comment by viquezclaudio** [comment]
Done, we are using the current pubtestnet as production testnet
