### ISSUE TITLE
Migration: Exercise PoW Mainnet to a (potentially shortlived secondary) PoS Testnet migration

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#2503]
While testing the migration on the PoW Testnet will provide a lot of insight, a PoW Mainnet migration ultimately will be necessary.  This migration should likely target a short lived secondary instance of a PoS Testnet as using Mainnet keys in Testnet should not be encouraged. 

As The process generally burns funds on the PoW Chain in order to i.e register a validator appropriate measures must be taken to make this a seamless process where participants are not losing any of their funds in the process.

**Comment by viquezclaudio** [comment]
Closing it as this was already done
