### ISSUE TITLE
State sync doesn't complete because last chunk cannot be applied

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2576]
While testing locally with the devnet script scenario with the following characteristics:

- 6 validators: 3 as history nodes, 3 full nodes
- 1 spammer, sending transactions at 500tpb
- 1 seed node
- 2 validators killed at the same time
- batches_per_epoch: 10
- transaction_validity_window: 5
- full_sync_threshold: 1

One of the full nodes is restarted, and it reaches a point where state sync is  ~99.84% complete, but the chunk cannot be committed because:

`Commit chunk for block e6e4a0d84a3bc914823b83e725907fcd28ac4077527a7cc8ccf7ad84554dcc7f failed: Error during chunk processing: Tree is already complete.`

However state sync is incomplete and doesn't finish, thus, the node cannot achieve consensus.

[StateSyncIncomplete.log](https://github.com/user-attachments/files/15774700/StateSyncIncomplete.log)

**Comment by viquezclaudio** [comment]
There are other _interesting_ things to note based on the logs:

- State sync is apparently started multiple times
- Several commit chunks are ignored
- Some chunk was not applied because of `The root node doesn't have the correct hash!`

**Comment by viquezclaudio** [comment]
Full logs including all validators:
[20240610_165651.zip](https://github.com/user-attachments/files/15774763/20240610_165651.zip)

**Comment by viquezclaudio** [comment]
I found this issue while testing with this fix: #2564 

However I cannot reproduce this issue if I revert #2564

**Comment by sisou** [comment]
How was it solved?

**Comment by viquezclaudio** [comment]
This was introduced by @styppo initial fix to the vanishing problem (https://github.com/nimiq/core-rs-albatross/pull/2564)
since that was not merged and the vanishing peers problem was fixed via other solution, this is no longer an issue
