### ISSUE TITLE
Full nodes need to be able to sync the validity window with other full nodes.

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2592]
With the light history store, full nodes rely on history nodes to provide the history chunks to sync the validity window.

This creates the problem that full nodes can only sync with history nodes, and they can no longer sync with other full nodes.

**Comment by viquezclaudio** [comment]
Previously, before the light history store, full nodes had a regular history store and they at least kept that previous epoch there, so they could provide the history chunks needed to sync the validity window. This is no longer the case.

**Comment by styppo** [comment]
Completed

**Comment by sisou** [comment]
Completed by not having a light history story anymore, right? So now all full nodes have the same history store and can supply the validity window.

**Comment by viquezclaudio** [comment]
Correct
