### ISSUE TITLE
Staking transactions are not enforced to be to / from the staking contract

### ISSUE THREAD

**Issue by danimoh** [nimiq/core-rs-albatross#2605]
`verify` of `Transaction` currently checks that the `Staking` sender / recipient type must be set, if the the sender / recipient address is the staking contract, but does not enforce that the sender / recipient must be the staking contract, if the sender / recipient sender type is `Staking`.
Verification of the sender / recipient data, and potentially later processing of the data, are solely based on the sender / recipient type though.
Thus, it might be possible to, for example, send a transaction that is interpreted as a staking transaction, via the `Staking` sender / recipient type, which is not in fact to / from the staking contract.

https://github.com/nimiq/core-rs-albatross/blob/bf6bab5b938ef158f58fae4347276f2581d5102a/primitives/transaction/src/lib.rs#L337-L349

PS: I did not confirm the issue on-chain, just filing this issue based on reading the code.

**Comment by styppo** [comment]
There is a check [here](https://github.com/nimiq/core-rs-albatross/blob/2abf923bd73877a7e45f239756195646d60da9f9/primitives/account/src/accounts.rs#L133) that the target account has the correct type when applying the transaction, so a transaction with an invalid sender/recipient type would not be accepted. We could however add an additional check to the intrinsic transaction verification to reject such transactions early, i.e. before attempting to apply them.

**Comment by sisou** [comment]
With the existing check, the transaction can still enter the mempool I guess? But then not get accepted into block, so filling up the mempool?
