### ISSUE TITLE
Extend ControlTransaction validation

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#2631]
With #2627 some validation checks around `ControlTransaction`s were added. This should get extended with more checks in order to be considered valid. Since this would be a breaking change, we will address this in a follow up PR.

Reference: [review](https://github.com/nimiq/core-rs-albatross/pull/2627#pullrequestreview-2122734670)

**Comment by hrxi** [comment]
As @sisou commented in https://github.com/nimiq/core-rs-albatross/pull/2627#discussion_r1643011951:

> Signaling transactions also have `TransactionFlags::SIGNALING` set, but AFAIK the combination of that flag and zero value is already checked in the transaction's internal validity and/or parser.
>
> The parsed `IncomingStakingTransactionData` has a `.is_signaling()` method:
>
> https://github.com/nimiq/core-rs-albatross/blob/21d91b3187e234c3319d9e3d774512fb04eb3c35/primitives/transaction/src/account/staking_contract/structs.rs#L90
