### ISSUE TITLE
Panic `history_store.prove_chunk` for full node is unimplemented

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#2639]
### General information

- Library version(s): v0.22.2
- Node type: full node
- Validator: yes
- Caller: https://github.com/nimiq/core-rs-albatross/blob/albatross/consensus/src/messages/handlers.rs#L160

[panic-light-history-store.log](https://github.com/user-attachments/files/15886094/panic-light-history-store.log)

**Comment by Eligioo** [comment]
This is the syncing history node which possibly made the requests to the full node. Which it shouldn't do.

[history-node-sync-from-scratch.log](https://github.com/user-attachments/files/15886772/history-node-sync-from-scratch.log)

**Comment by viquezclaudio** [comment]
The exact reason why those requests were made is still unclear, however, we should not panic if this happens.
#2642 will take care of this and log who made those requests for debugging purposes.

**Comment by nibhar** [comment]
> [history-node-sync-from-scratch.log](https://github.com/user-attachments/files/15886772/history-node-sync-from-scratch.log)

I don't see a panic in there. What is this log showing?

**Comment by viquezclaudio** [comment]
The panic is located in the full node, not the history node (first logs in this issue)

`thread 'tokio-runtime-worker' panicked at 'not implemented': blockchain/src/history/light_history_store.rs:391`

**Comment by viquezclaudio** [comment]
Closing this one, as this is no longer an issue because full nodes now have the history store as per #2692
