### ISSUE TITLE
Validator unable to complete state sync

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2662]
Validator, when configured as a full node, is unable to sync because is continually requesting, and discarding, the same state sync chunk.

[pubtestnet_validator5.log.zip](https://github.com/user-attachments/files/15924567/pubtestnet_validator5.log.zip)

**Comment by viquezclaudio** [comment]
Should be fixed by #2679 ,  #2677  , #2642

As all of the above are observed in the logs.

**Comment by viquezclaudio** [comment]
Closing the issue as the relevant PRs were merged

**Comment by sisou** [comment]
The third PR you mentioned is not yet merged.

**Comment by viquezclaudio** [comment]
Yes but that only influences the panic observed in the logs which already reported by #2642 
The part related to state sync not completed is already fixed
