### ISSUE TITLE
Remove `RewardTransaction` from `MacroBody`

### ISSUE THREAD

**Issue by hrxi** [nimiq/core-rs-albatross#2698]
It was added in #1280 to be able to simulate reward transactions with incomplete state but it's no longer required since #1634 because we use trie diffs instead of transactions for syncing.

**Comment by styppo** [comment]
The reward transactions are still required for state sync. We can update the accounts tree using trie diffs while the state is incomplete, but we still need the reward inherents to update the history which we can't compute without the staking contract.
