### ISSUE TITLE
`Instant` crate is no longer maintained

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#2729]
Using `web-time` is suggested to use instead.

https://github.com/sebcrozet/instant/commit/d94bebae9fa470869dda4c1c916ac3686c7bc9bd

**Comment by sisou** [comment]
Unmaintained doesn't mean broken. But in any case, should be easy to replace, as it's in two of our subcrates only I believe (the abstraction in utils and in web-client).

**Comment by sisou** [comment]
Hmm. I'm mistaken: https://github.com/search?q=repo%3Animiq%2Fcore-rs-albatross+%22instant+%3D%22&type=code

**Comment by hrxi** [comment]
Doesn't seem particularly necessary to replace.

**Comment by Eligioo** [comment]
Closed since now it's a duplicate of #3052
