### ISSUE TITLE
Panic in tokio-runtime-worker (x2)

### ISSUE THREAD

**Issue by joeleol** [nimiq/core-rs-albatross#2730]
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): v0.22.3
- Browser version(s): N/A
- Devices/Simulators/Machine affected: History Node (RPi5 / 8GB / 2xNVME (RAID 1)
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: None

#### Expected behavior

The panics not to happen. 

#### Actual behavior

The panics happen.

#### Steps to reproduce

When restarting the client after it had lost consensus, I am unable to regain consensus and also seem to have a corrupted DB. 

#### Crash log? Screenshots? Videos? Sample project?

Please see attached screenshot, I will start logging persistently now. 

I can also make the db available if required. 

![photo_5780686253254101922_w](https://github.com/nimiq/core-rs-albatross/assets/64198137/f40746a0-d6c0-4f97-b1f1-9adb18424531)

**Comment by ii-cruz** [comment]
This seems to be related to the merge of #2692 and/or some other changes regarding the serialization of transactions that made the previous database incompatible with the new and better-performing one.
