### ISSUE TITLE
CI run - Panic Trying to revert macro block

### ISSUE THREAD

**Issue by ii-cruz** [nimiq/core-rs-albatross#2790]
Panic validator 2

CI run https://github.com/nimiq/core-rs-albatross/actions/runs/9922584262

**Comment by Eligioo** [comment]
Closed with #2752.

In the following scenario:
- The first batch in the first epoch of the chain has some transactions,
- A macro block gets produced and we proceed to the next batch,
- This new batch doesn't contain any transactions and we try to push with history sync (`Blockchain::push_history_sync`)

The known history returned by getting the `get_nonfinal_epoch_transactions` goes over a macro block. Causing to create a `diverging_block` before the macro block we already have, when reverting to a common state, resulting into reverting beyond this macro block. Which shouldn't be possible.

A test should catch this, which I will create.
