### ISSUE TITLE
Cannot create example config when .nimiq dir doesn't exist

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#2846]
When starting a client without any command line arguments on a "clean" system, it looks for the config file at `$HOME/.nimiq/client.toml`. If that doesn't exist, it fails with a configuration error:

```
Configuration error: Config file not found. Please create one at /home/<user>/.nimiq/client.toml or specify a location using -c path/to/config.toml, see the example config file at /home/<user>/.nimiq/client.toml.example
```

But that error says the user should look for the example config file at `$HOME/.nimiq/client.toml.example`. But that also failed to create if the `.nimiq` directory does not already exist (curiously, there should be an `info` and a `warn` log about that, but those do not show?).

The relevant code is:

https://github.com/nimiq/core-rs-albatross/blob/04340beadf69a271ec5e4661c230236eb4d4600b/lib/src/config/config_file/mod.rs#L85-L107

Furthermore, because the example-config-creating code runs before the config file is read, a new example config file is created again after the user renamed the example file to `client.toml`.

### Issues
- [ ] `.nimiq` directory is not created, so example config file can not be written
- [ ] Failure to write example config file fails silently (logs are not printed)
- [ ] Example config file is written again, even if main config file exists

Related PRs:
- #2401 by @Eligioo
- #2414 by @hrxi

**Comment by Twinkym** [comment]
`use std::fs;
use std::fs::create_dir_all;
use std::path::Path;;

fn create_config_files() -> Result<(), Error> {
    // Directory where configuration files are stored.
    let config_dir = paths::home();

    // Check if the directory exists, if not, create it.
    if !config_dir.exists() {
        log::info!("Creating config directory at: {}", config_dir.display());
        if let Err(e) = create_dir_all(&config_dir) {
            log::error!(
                "Failed to create directory: {}: {}", config_dir.display());
                e, config_dir.display()
            );
            return Err(Error::config_error("Failed to create config directory"));            
    }
}

// Path to configuration file.
let path_example = config_dir.join("client.toml.exe");

// Path to the main configuration file.
let path = config_dir.join("client.toml.");

// Check if the main file already exists before creating the sample file.
if !path.exists() {
    // If the sample file does not exist, create one.
    if !path_example.exists() {
        log::inifo!("Creando ejemplo de configuración en: {}", path_example.display());
        if let Err(e) = fs::write(&path_example, Self::EXAMPLE_CONFIG) {
            log::error!(
                "Failed to create example config file: {}: {}",
                e, path_example.display()
            );
            return Err(Error::config_error("Failed to create example config file"));
        
        }
    }

    // Informs the user that the main configuration file does not exist.
    let msg = format!(
        "Config file not found. Please create one at {} or specify a location using -c path/to/config.toml, see the example config file at {}",
        path.display(),
        path_example.display(),
    );
    log::warn!("{}", msg);
    return Err(Error::config_error(&msg));
}

ok(())
}
`   
Here I share my solution to your problem, hope it serves well. greetings. ATT: David De La Puente.
