### ISSUE TITLE
Mempool transaction verification is wrapped in `spawn_blocking`

### ISSUE THREAD

**Issue by Eligioo** [nimiq/core-rs-albatross#2852]
This is probably redundant
https://github.com/nimiq/core-rs-albatross/blob/albatross/mempool/src/verify.rs#L43-L47

**Comment by Eligioo** [comment]
Additionally, the default for `max_blocking_threads` ([link](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.max_blocking_threads)) for the Tokio runtime is 512 thus concurrently verifying more than this number currently probably doesn't work as expected.

**Comment by styppo** [comment]
Fixed in cee38d8b4fdaabd1f06969c7168adc59120caac8
