### ISSUE TITLE
Panic: Peer is connected

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2853]
Observed in the spammer, during a private testnet execution.

`Aug 20 22:01:50 spammer-1 nimiq-spammer[1018802]: 2024-08-20T22:01:50.479430808Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Peer is connected.': /home/nimiq/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libp2p-autonat-0.13.0/src/v1/behaviour/as_server.rs:304
    0: <backtrace::capture::Backtrace as core::default::Default>::default
    1: log_panics::Config::install_panic_hook::{{closure}}
    2: std::panicking::rust_panic_with_hook
    3: std::panicking::begin_panic_handler::{{closure}}
    4: std::sys_common::backtrace::__rust_end_short_backtrace
    5: rust_begin_unwind
    6: core::panicking::panic_fmt
    7: core::panicking::panic_display
    8: core::option::expect_failed
    9: <libp2p_autonat::v1::behaviour::as_server::AsServer as libp2p_autonat::v1::behaviour::HandleInnerEvent>::handle_event
   10: <libp2p_autonat::v1::behaviour::Behaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   11: <nimiq_network_libp2p::behaviour::Behaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   12: libp2p_swarm::Swarm<TBehaviour>::poll_next_event
   13: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
   14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
   15: <core::pin::Pin<P> as core::future::future::Future>::poll
   16: tokio::runtime::task::core::Core<T,S>::poll
   17: tokio::runtime::task::harness::Harness<T,S>::poll
   18: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   19: tokio::runtime::scheduler::multi_thread::worker::Context::run
   20: tokio::runtime::context::scoped::Scoped<T>::set
   21: tokio::runtime::context::runtime::enter_runtime
   22: tokio::runtime::scheduler::multi_thread::worker::run
   23: tokio::runtime::task::core::Core<T,S>::poll
   24: tokio::runtime::task::harness::Harness<T,S>::poll
   25: tokio::runtime::blocking::pool::Inner::run
   26: std::sys_common::backtrace::__rust_begin_short_backtrace
   27: core::ops::function::FnOnce::call_once{{vtable.shim}}
   28: std::sys::pal::unix::thread::Thread::new::thread_start
   29: <unknown>
   30: <unknown>`

**Comment by viquezclaudio** [comment]
Full logs:
[privtestnet_spammer1.log](https://github.com/user-attachments/files/16747984/privtestnet_spammer1.log)

**Comment by Eligioo** [comment]
Fixed by https://github.com/libp2p/rust-libp2p/pull/5597

**Comment by Eligioo** [comment]
Issue is no longer relevant. Panic occurred in AutoNAT V1 but moved to V2 eventually with PR #2955.
