### ISSUE TITLE
Full nodes unable to sync to public testnet

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#2872]
Full nodes are currently unable to sync with the public testnet:

Just live sync:

[full-node-unable-sync (1).log](https://github.com/user-attachments/files/16835018/full-node-unable-sync.1.log)

Validity sync & live sync are happening at the same time:
[validity_sync&live_sync.log](https://github.com/user-attachments/files/16835046/validity_sync.live_sync.log)

**Comment by Eligioo** [comment]
As discussed we only start accepting info from live sync, if we can enforce the validity.

**Comment by Eligioo** [comment]
Closed with #2877 and #2882
