### ISSUE TITLE
Failed to build npm (wasm) package in CI

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#3022]
CI fails to build the npm wasm package, retry also failed with same error:

https://github.com/nimiq/core-rs-albatross/actions/runs/11676122517/job/32564694138

**Comment by jsdanielh** [comment]
Looks like there is an issue filed in wasm-pack related to this: https://github.com/rustwasm/wasm-pack/issues/1441

**Comment by sisou** [comment]
So according to that issue a workaround would be to force building with Rust 1.81 instead of latest.
