### ISSUE TITLE
RPC method send_new_staker_transaction doesn't work?

### ISSUE THREAD

**Issue by redmaner** [nimiq/core-rs-albatross#303]
### General information

- Library version(s): albatross branch, commit = https://github.com/nimiq/core-rs-albatross/commit/d8ae3ca7a458fe7de06f85d142746b3b33a21e52

## Bug report
Maybe a bug, maybe a lack of understanding. Hopefully the latter. I have been trying to get the new RPC method `send_new_staker_transaction` to work, without any luck. Looking at the code, @sisou 's arpl tool and the RPC interface I think I'm doing it right, but I constantly get the error `Transaction rejected: Invalid` indicating the transaction is wrong. 

The steps I followed:
* created a new account 
* gave the account a balance of 33600000
* unlocked the account 
* send a new staker transaction to active validator `NQ79 VVKK SSCG HJUJ KFHV EA1Y NEJ6 6P7S ST56`, which is node 3 in the docker setup 

#### Expected behavior
The transaction succeeds 

#### Actual behavior
The transaction is rejected. I have tried several things that all lead to the same result:
* using different addresses for validator, the validator address, reward address, warm address
* tried both an actual validatity_start_height number and the new "+0" 
* tried with tx_fee, without tx_fee 

#### Steps to reproduce

See above

#### Crash log? Screenshots? Videos? Sample project?
A log from my script
```
[2021-09-05] [19:28:29.159] [info] pid=<0.337.0> address=NQ27 LJRK 1TXE MN0Y JMDC ML3V 9VR8 DT7N A8A8  | Created account
[2021-09-05] [19:28:29.167] [info] pid=<0.337.0> address=NQ27 LJRK 1TXE MN0Y JMDC ML3V 9VR8 DT7N A8A8  | Account has received balance 33600000
[2021-09-05] [19:28:35.055] [info] pid=<0.337.0> address=NQ27 LJRK 1TXE MN0Y JMDC ML3V 9VR8 DT7N A8A8  | Account has been imported and unlocked
[2021-09-05] [19:28:35.055] [info] pid=<0.337.0> address=NQ27 LJRK 1TXE MN0Y JMDC ML3V 9VR8 DT7N A8A8  | Starting stake transaction to validator NQ79 VVKK SSCG HJUJ KFHV EA1Y NEJ6 6P7S ST56, with stake balance 22176000
[2021-09-05] [19:28:35.061] [error] pid=<0.337.0>  | Encountered error for call send_new_staker_transaction: {-32603, "Internal error", "Transaction rejected: Invalid"}
```

I checked the Albatross logs, but didn't find anything useful as to indicate why this happens. I checked the trace logs that are used within this function https://github.com/nimiq/core-rs-albatross/blob/596a38b5799ef6421d610c3fead6347889b146a8/primitives/account/src/staking_contract/validator.rs#L77 but the only trace log I could find was ` 2021-09-05 17:21:36.123 TRACE traits               | Trying to put the staking contract in the accounts tree.` but I saw this is also logged in other instances, so no idea if that is helpful. 

<b>The big question:</b> Is this a bug, or am I just missing something? Thanks in advance!

**Comment by sisou** [comment]
Thanks for reporting, this is a bug.

We are starting to investigate, and so far we know that the staking contract is not (or not correctly) stored in the generated Genesis block and thus accounts tree, so it cannot accept transactions meant for a staking contract.

We'll let you know if we figure it out before Bruno gets back :)

**Comment by redmaner** [comment]
Thanks! I'll await further updates then.

**Comment by sisou** [comment]
I just pushed a hotfix that should enable sending transactions to the staking contract.
It will need a more permanent solution, though, so I'm leaving this issue open.

**Comment by redmaner** [comment]
Thanks, I can confirm it works now!

**Comment by brunoffranca** [comment]
The more permanent solution would be to change our Patricia Trie to only have one type of node that has both data and children. The way it works right now is that we have branch nodes (no data but can have children) and leaf nodes (can have data but no children).
That is something that we should do eventually, but for bigger reasons than just this issue. I'll close this since the solution found above works quite well.
