### ISSUE TITLE
`max_epochs_stored` should affect history store

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#3110]
Currently, the `max_epochs_stored` config option only affects the chain store, but not the history.
Also, the `saturating_sub` always deletes the first epoch, even if not intended.

See: https://github.com/nimiq/core-rs-albatross/blob/d39203fa1d7e53fd158dd2368ec733792d895976/blockchain/src/blockchain/push.rs#L370

**Comment by sisou** [comment]
Blocks and transactions before the last epoch are gone with the wind...
