### ISSUE TITLE
Inconsistencies in the naming of web client methods

### ISSUE THREAD

**Issue by Albermonte** [nimiq/core-rs-albatross#3127]
- [x] `PublicKey` missing `fromAny`
- [x] `Transaction` missing `deserialize`, but `serialize` does exist. (Using `fromAny` does the same as `deserialize`)
- [x] `Address` missing `deserialize`, but `serialize` does exist.
- [x] Missing `PlainTransactionFlag` enum. Need to use `0b1` or `0b10`, but no types for it too.
- [ ] Missing `Account.TYPE_MAP` that was present in [core-js](https://github.com/nimiq/core-js/blob/6452745183175def19a0acdadafaa7527c02940d/dist/types.d.ts#L1291)

**Comment by sisou** [comment]
@Albermonte How important is the `Account.TYPE_MAP` to you? I don't think it would work currently.

**Comment by Albermonte** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/14013679?s=64&amp;u=78a9a05ea79ffb3cbaad377e8921c75e6df478d4&amp;v=4">@Albermonte](https://github.com/Albermonte) How important is the `Account.TYPE_MAP` to you? I don't think it would work currently.

1/10
You can omit it
