### ISSUE TITLE
Wrong content-type header in RPC responses

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#3130]
The rpcserver crate is returning `application/json-rpc` instead of just `application/json`. This is there since that crate was created.

https://github.com/nimiq/jsonrpc/blob/a089737987cdff99f1271f2f8a7fd547fdea3621/server/src/lib.rs#L220

This is messing with some service providers/exchanges automated setup.

**Comment by hrxi** [comment]
I couldn't find an official mime type for JSONRPC in the spec, so I guess we can just change to `application/json` if that's useful to some people.

**Comment by sisou** [comment]
@hrxi I made the commit in https://github.com/nimiq/jsonrpc, can you please make a release and use it in core-rs-albatross?

**Comment by jsdanielh** [comment]
Fixed in #3138.
