### ISSUE TITLE
How to import the address of pow node to pos node?

### ISSUE THREAD

**Issue by jack-dot-wu** [nimiq/core-rs-albatross#3161]
I'm from exchange. And so many addresses of users in pow node, But how to import it into pos node? Or How to transfer the nimiq with it by pos node?

**Comment by Albermonte** [comment]
You are probably looking for this: https://www.nimiq.com/developers/migration/node-operators

**Comment by Eligioo** [comment]
@jack-dot-wu inside the your `core-js` folder you can find the `keytool` located in `clients/nodejs`. This tool helps you to export addresses from your `WalletStore` generated by your PoW node.

The `keytool` looks for a folder called `wallet` containing a file `data.mdb` in your **current working directory**. This means you should execute the `keytool` from the same directory as where the `wallet` directory is located. Usually you can find the `wallet` folder inside `clients/nodejs` or in the root of `core-js`.

`node keytool.js help` --> Show help dialog.
`node keytool.js list` --> List all generated addresses currently in the `WalletStore`.
`node keytool.js export --address ADDRESS --format hex` --> Export the private key of a specific address in hex format.

The exported private key in hex format, can be imported in your PoS node via the [`importRawKey` RPC method](https://www.nimiq.com/developers/build/set-up-your-own-node/rpc-docs/#importrawkey).

Feel free to re-open this issue if you feel the need for it.
