### ISSUE TITLE
```createBasicTransactionWithData``` empty response

### ISSUE THREAD

**Issue by blouflashdb** [nimiq/core-rs-albatross#3197]
Calling this in my bash:
```
curl --request POST --url http://127.0.0.1:8648 --header 'Content-Type: application/json' --data '{"jsonrpc": "2.0","method": "createBasicTransactionWithData","params": ["NQXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX", "NQXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX", "data", 1, 0, "+0"],"id": 1}'
```

gives me this response:
```
curl: (52) Empty reply from server
```

**Comment by Eligioo** [comment]
The server actually fails to process this request as expects the `data` field to be in a hex representation. If you fail to do so the server simply panics which is incorrect behaviour.

It being clear that a hex format must be provided is among of the improvements of the RPC docs and server.
