### ISSUE TITLE
Rebranching during macro block production (missing test scenario)

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#321]
At Macro block production we need to make sure that micro blocks in that batch can still be rebranched. If a Validator receives a block on a better chain for which it does not know the predecessor it needs to request the missing blocks and rebranch to that better chain accordingly, entering either micro or macro block production as necessary.

A test scenario is needed for this case, and here's a brief summary of what it could look like.

- Have a network progress to the last micro block of a batch.
- Disconnect the node producer for the last micro block and let him produce it (Node A). This node should have few enough slots such that the others can progress without it, but not by much.
 - This producer will now enter macro block production
- the remaining nodes will view change
- the new block producer produces the block.
- disconnect enough other nodes such that macro block production needs node A to progress.
- reconnect Node A.

The expected behaviour would be that Node A sees a proposal for a chain predecessor it does not know and it should thus request it. In turn that should trigger a rebranch and Node A should enter macro block production on the (better) chain that the other nodes are on, progressing the Network.

**Comment by viquezclaudio** [comment]
The test scenario described in this issue is still missing.
