### ISSUE TITLE
Investigate use of Poseidon hash into nano-zkp

### ISSUE THREAD

**Issue by brunoffranca** [nimiq/core-rs-albatross#336]
Poseidon hash (https://www.poseidon-hash.info/) is a algebraic hash function designed specifically for use in zero-knowledge systems like SNARKs. It is supposedly 8x faster than Pedersen hash. It also has the advantage that it maps field elements to field elements.
Investigate if we can use it in our nano-zkp crate. An obvious candidate is the PK tree, where we can substitute the costly serialization and Pedersen hash for the Poseidon hash. This might allows us to reduce the number of leaves in the PK Tree or perhaps to get rid of the PK Tree completely (less likely).

**Comment by paberr** [comment]
Initial benchmarks suggest that Poseidon hash is slower than Pedersen outside the ZKP.

```
test poseidon_uncompressed ... bench: 427,008,925 ns/iter (+/- 138,609,399)
test pedersen_uncompressed ... bench: 193,907,129 ns/iter (+/- 12,560,747)
```
