### ISSUE TITLE
Unpark validators automatically

### ISSUE THREAD

**Issue by vlvrd** [nimiq/core-rs-albatross#344]
Validators should be able to recognize if they have been parked in the staking contract so that they can send an unpark transaction and prevent being automatically inactivated.

**Comment by sisou** [comment]
Unparking requires the validator _warm_ key, which currently needs to be passed into the transaction creation function.

It would be great if instead of passing the private key, the function could search the available unlocked wallets in the node to sign the tx instead.

**Comment by vlvrd** [comment]
@sisou I'm going to open a separate issue to track wallet related tasks (as soon as we discuss them) where I'll include support to search available unlocked wallets to sign the tx 👍
