### ISSUE TITLE
Panic while peer is reconnecting

### ISSUE THREAD

**Issue by jeffesquivels** [nimiq/core-rs-albatross#379]
The following panic was observed while testing a disconnect + reconnect scenario with four validators:

`2021-10-22 11:36:53.639 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'assertion failed: self.peer_id.is_none()': network-libp2p/src/message/handler.rs:159`

**Comment by jeffesquivels** [comment]
The panic is the result of an assertion in the code that is meant to prevent us from adding a new peer that already exists.. Initially it seems the assertion is correct and the problem is that either the peer is reconnecting without being disconnected or we didn't realized the peer was disconnected.

In the logs one can observe several cases of connection -> disconnection -> reconnection before the panic, so this may be related.

**Comment by viquezclaudio** [comment]
[20211101_204032_self_id_none_trace.zip](https://github.com/nimiq/core-rs-albatross/files/7462587/20211101_204032_self_id_none_trace.zip)
Attaching trace logs for this issue
