### ISSUE TITLE
Database errors related to readers locktable

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#393]
Under load, we sometimes encounter the following LMDB errors:
`Error::Code(-30790, 'MDB_READERS_FULL: Environment maxreaders limit reached')`
and
`Error::Code(-30783, 'MDB_BAD_RSLOT: Invalid reuse of reader locktable slot')`.

Both are related to the [readers lockable](http://www.lmdb.tech/doc/group__readers.html).

The `MDB_READERS_FULL` error typically occurs if there are more threads than slots (default: 126 slots).
In LMDB, every thread is assigned one FIXED slot on the lock table (except if NO_TLS is used). So, the error should really only occur if we have more threads than reader slots.
We should check whether we really have such a large amount of threads! Also, I'm not sure what happens if we close threads and open new ones. Will old lock table entries be reused?

The `MDB_BAD_RSLOT` error could have two causes: trying to open two read transactions on one thread or trying to move a read transaction across threads (Transactions are not Send, so this should not be possible). It seems that this can also happen if you fork a process with a database connection (which I do not think we do).

Both of the issues could be investigated using the [`reader_check`](https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/struct.Environment.html#method.reader_check) method. There is also a `mdb_reader_list` method, which unfortunately is not exposed by lmdb-zero. We should also check the maximum number of threads Tokio uses.

**Comment by paberr** [comment]
Since we use the `tokio::main` annotation, the number of worker threads is:
> The worker_threads option configures the number of worker threads, and defaults to the number of cpus on the system. This is the default flavor.

Apparently, this kind of error also happens if multiple processes have the same LMDB open and do not properly close transactions. I read about the same error message in mimblewimble (https://github.com/mimblewimble/grin/issues/1822), where improperly closed processes were the issue. https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/169 hints towards the same problem (improperly closed processes).

We only have a single process running, however, and Rust should ensure all transactions to be destroyed properly (except maybe if threads panic?).

We can also open the same database in another process and use `mdb_stat` for debugging.

**Comment by viquezclaudio** [comment]
Attaching logs
[20211104_115120_spammer_lmdb_panic.zip](https://github.com/nimiq/core-rs-albatross/files/7478192/20211104_115120_spammer_lmdb_panic.zip)
:

**Comment by paberr** [comment]
@viquezclaudio was able to reproduce the bug and we used `reader_check` to see whether there are any stale readers. Answer is: no.
Additional observation: it only ever appeared in the transaction spammer.

**Comment by viquezclaudio** [comment]
[20211105_002537_lmdb_extra_logs.zip](https://github.com/nimiq/core-rs-albatross/files/7479653/20211105_002537_lmdb_extra_logs.zip)

**Comment by paberr** [comment]
Seems I found the issue with regards to the `MDB_READERS_FULL`.
According to [this](https://github.com/tokio-rs/tokio/discussions/3858):
> Blocking threads. Tokio will not spawn any blocking threads until they are needed due to calls to spawn_blocking. Since blocking tasks are not async, each blocking thread can work on only one spawn_blocking task at the time. More blocking threads are spawned if more spawn_blocking tasks are spawned at the same time, up to some upper limit (which is around 500 by default). Beyond the upper limit, tasks are put in a queue until one of the existing threads finish their work. The threads are shut down again if no new tasks are spawned within 10 seconds.

The transaction spammer uses blocking threads and spawns them *very* frequently. So likely we will exceed the 126 max. readers.

**Comment by paberr** [comment]
Chances are that the `MDB_BAD_RSLOT` error was related. We haven't seen it in a while, so I'm going to assume it's fixed until we see it again.

Our own code also makes use of `spawn_blocking` a lot. So, I introduced a config option for the max_readers and set it to 600, which should be sufficient for up to 87 cpu cores (according to Tokio's defaults).
Initially, I also thought about adding config parameters for Tokio's parameters. However, they would have to be set before the config is loaded.
