### ISSUE TITLE
Batch rewards not consistently requestable as inherents

### ISSUE THREAD

**Issue by redmaner** [nimiq/core-rs-albatross#406]
### General information

- Library version(s): albatross branch, commit: b6e2ad7cdcf39dfd4f5554907ae94659a6dc0ac8

## Bug report
Before the merge of the RPC fixes with PR https://github.com/nimiq/core-rs-albatross/pull/352 every batch except for the first batch contained the batch rewards for the active validators as inherents, which could be requested via the method `getBatchInherents`. After the PR this is no longer the case. I requested the the batch inherents for the first 100 batches, but only a few batches contained the batch rewards of validators. 

### Question
Is this intended behavior and has the payout of rewards to validators been changed or is this possibly a bug?

#### Steps to reproduce
Run the four validators in docker using the compose file and docker files attached with the repo. Call the method `getInherentsByBatchNumber` for the first 100 batches.

**Comment by brunoffranca** [comment]
There was a bug in the HistoryStore that was causing problems with several RPC methods. I just pushed a commit that fixed that (ef4fd75). It probably solves your issue.

**Comment by redmaner** [comment]
Thanks, I'll try tomorrow and let you know

**Comment by sisou** [comment]
I just tested with that new commit and it works reliably now :+1:
