### ISSUE TITLE
Mempool no longer completely validates transactions

### ISSUE THREAD

**Issue by jeffesquivels** [nimiq/core-rs-albatross#415]
The new mempool implementation, by design, does only very basic checks on the transactions it gets before storing them which results in cases where transactions that will fail are passed to the block production logic ([this CI fail](https://github.com/nimiq/core-rs-albatross/runs/4172647404?check_suite_focus=true) seems to be a case of that, for example).

Basically there are two ways to deal with this: either we do a more thorough check before/during the block production phase or we allow blocks to include transactions that will fail. The former one would be in line with how this is handled on Nimiq 1.0, but would, most likely, have a performance degrading impact. The latter one is more disruptive (it's a change to user-facing behaviour from what we used to have and could introduce new possible attacks that need to be prevented).

**Comment by brunoffranca** [comment]
Spooky. I was just now looking into that fail. And was thinking the same.

**Comment by brunoffranca** [comment]
The second option is especially tricky. If we allow transactions to be no-op then we need a way of communicating that to the users. In Ethereum they have receipts to do this, but we don't have anything. Our users would just be looking at their transaction in the block and not knowing if it had any effect in the chain or not.
First option is a lot simpler. We would get the transactions for the block from the mempool, do a full verification, remove the ones that don't pass and then finish the block. However this will result blocks that are smaller than intended (unless you go to the mempool again to fetch more transactions). The main problem is DoS attacks. If the mempool accepts transactions that are not valid then I can spam you quite easily.

**Comment by brunoffranca** [comment]
BTW, why was the spammer pushing invalid transactions?

**Comment by jeffesquivels** [comment]
> BTW, why was the spammer pushing invalid transactions?

In this case the transaction didn't come from the spammer, but from the automatic unpark functionality in the validator: in the logs for the original post's CI fail this can be seen:

` 2021-11-10 23:20:42.738 ERROR validator            | Tried to unpark a validator that was already unparked! It has address NQ67 0FC5 7CQL Q4PK UUPA 4H2R JHPE HSRJ U1SQ.
 2021-11-10 23:20:45.008 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: InvalidForRecipient': block-production/src/lib.rs:87`
 
Which means the problem is caused because the transaction caused [this code](https://github.com/nimiq/core-rs-albatross/blob/6c48586c8d349d2fa1878b3e6a0c0b7805d69d74/primitives/account/src/staking_contract/validator.rs#L517-L523) to be executed, which makes sense since that function is called from [Staking Contract's `commit_incoming_transaction`](https://github.com/nimiq/core-rs-albatross/blob/6c48586c8d349d2fa1878b3e6a0c0b7805d69d74/primitives/account/src/staking_contract/traits.rs#L159) which is called all the way up from the line that is panicking (since it didn't `expect` the `Result` of `get_root_with()` to be an `Err`).

**Comment by viquezclaudio** [comment]
More instances of the same issue in our CI executions:
https://github.com/nimiq/core-rs-albatross/runs/4194527290?check_suite_focus=true
https://github.com/nimiq/core-rs-albatross/runs/4193562798?check_suite_focus=true
https://github.com/nimiq/core-rs-albatross/runs/4212024956?check_suite_focus=true
