### ISSUE TITLE
Stop a block producer with an old state from querying the blockchain

### ISSUE THREAD

**Issue by jeffesquivels** [nimiq/core-rs-albatross#428]
Sometimes a block producer will keep running in parallel to a rebranch operation and then it will try to query the blockchain (which is now in on the new branch) with it's own stale state.

Since 90ea8354148e63ae02acbf18f3f9133f8135aa1e, this will log a warning instead of panicking (since this block producer will eventually be dropped and a new one created with the right state, this issue shouldn't last for long).

We should still try to fix this in a way that completely prevents the querying of the blockchain with data that is incosistent with its current state, and that is what this issue is for.

**Comment by jeffesquivels** [comment]
Some CI runs (with logs) where we ran into this issue (when it was a panic):

https://github.com/nimiq/core-rs-albatross/runs/4180299893?check_suite_focus=true
https://github.com/nimiq/core-rs-albatross/runs/4191934054?check_suite_focus=true
https://github.com/nimiq/core-rs-albatross/runs/4195406721?check_suite_focus=true

**Comment by jsdanielh** [comment]
Already fixed
