### ISSUE TITLE
Review the current accounts tree implementation 

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#432]
After the last accounts tree refactor, there is some functionality that is missing (such as accounts pruning), which would helped mitigating issues like [417](https://github.com/nimiq/core-rs-albatross/issues/417). The idea of this task is to do a general review of the accounts tree functionality to find holes or potential problems.

**Comment by brunoffranca** [comment]
If I'm not mistaken, the accounts are now pruned immediately upon a transaction. So there shouldn't be any "prunable" accounts in the Accounts Trie.
The PR #430 is very weird, especially these lines https://github.com/nimiq/core-rs-albatross/pull/430/files#diff-7b33a1b9e51a684fa5c6dbe676f75ffb09387ae43273e1fa7a0b9fcf05a5a72cR173-R176 . The only way for `new_balance` to be zero is if `total_value` is also zero and the previous account balance was non-existent. So it seems we allow transactions from non-existent accounts as long as the total value of the transaction is zero.

**Comment by brunoffranca** [comment]
Ok, got it. That behavior was introduced right here a5ed6b7.

**Comment by viquezclaudio** [comment]
Correct, reverting an unpark transaction fails if we don't have this [fix](https://github.com/nimiq/core-rs-albatross/pull/430/files#diff-7b33a1b9e51a684fa5c6dbe676f75ffb09387ae43273e1fa7a0b9fcf05a5a72cR173-R176) in place, as this [test](https://github.com/nimiq/core-rs-albatross/blob/albatross/block-production/tests/mod.rs#L212) shows.
