### ISSUE TITLE
Store blocks on inferior chain

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#439]
Currently when pushing a block on an inferior chain the push resolves early with `PushResult::Ignored` without storing the block.

This has a number of issues, most prominently that a macro block can exist on any chain and if it does that chain also is the main chain, regardless of view changes. Macro blocks are final by definition and thus cannot be rebranched to a superior chain, and 2/3+1 validators agreed on this block.

Therefore all micro blocks that are valid blocks, no matter their chain ordering must be pushed to the chain store, as they can be referenced in the future. Only after a macro block is produced and successfully pushed, the blocks of inferior chains on the previous batch can be pruned.

**Comment by brunoffranca** [comment]
This is unworkable though. What if a malicious validator decides to create hundreds or thousands of forks? If everyone needs to store all of the forks then the network can be DoS'ed.
