### ISSUE TITLE
Albatross RPC Methods

### ISSUE THREAD

**Issue by riptl** [nimiq/core-rs-albatross#45]
- [x] `getProducer()`: query the producer of a block
 - [x] `slotState()`: get the active slots
 - [x] Staking contract information
 - [x] Wallet Staking calls
 - [x] Macro block prepare/commit progress
 - [x] View Change progress

**Comment by jgraef** [comment]
`getProducer` can be deprecated. The block producer is now included in the result of [`get_block`](https://github.com/nimiq/core-rs-albatross/blob/66290f6e50e065dc2deb4f724fee014ecc2d468c/rpc-server/src/handlers/blockchain_albatross.rs#L305)

**Comment by jgraef** [comment]
Live progress for pBFT prepare/commit/view-change doesn't make sense. We will have a websocket server for this soonish.

**Comment by jgraef** [comment]
I'll mark prepare/commit progress as done. It's not a live update, but #58 includes the justification in macro blocks.

**Comment by jgraef** [comment]
View change are also rendered now. No live updates here too, since we need a websocket server for that,

**Comment by jgraef** [comment]
I'll create an issue (or just an PR) for the websocket server soon(TM)
