### ISSUE TITLE
Possible way of getting rid of the unpark transaction

### ISSUE THREAD

**Issue by brunoffranca** [nimiq/core-rs-albatross#494]
When the parking mechanism was introduced the idea was to simply have a way of inactivating non-responding validators, so that they wouldn't keep getting selected. The current mechanism is this:

- A validator misbehaves. It gets added to the disabled slots and the parked set.
- If it does nothing, it will not be able to produce micro blocks and will be inactivated at the end of the epoch.
- If it sends an unpark transaction then it will be removed from the disabled slots and from the parked set.
The idea behind of the unpark transaction is that a validator that delays one single time shouldn't be prohibited of producing micro blocks for the rest of the epoch (and losing all the rewards). So we need a way of letting them say that they are back online. This is also tightly related to why we distribute rewards every batch, so that a single delay doesn't result in losing the rewards for an entire epoch.

However, we recently realized that there are some problems in having a "control transaction" like this. When there is a lot of traffic these transactions might not get through. Also, validators always need an account with some coins to pay fees for these transactions, which is a nuisance. Furthermore, when validators send an unpark transaction they need to monitor the chain and decide if they should resend the transaction or not. Overall, it's a lot of complexity.
I propose a simpler way of doing this. We really only care about not overly punishing validators that delay. Here's my proposed mechanism:

- Instead of having lost reward slots, disabled slots and parked set, we only have one hashmap that maps each slot to a number between 0 and 1. We'll call it the slash set or punishment map or whatever.
- Every slot starts the epoch at 1. If a slot delays a block, its number will decrease by some predetermined amount (0.1 for example). If a slot forks the chain, its number will go to 0 right away.
- At the end of the epoch (actually one epoch later) the reward that a slot would get is multiplied by its slash number. So if the number is 1 it gets the full reward, if it's 0.5 it gets half of the reward and so on.
- Also, if the number reaches 0 at any time, then the slot will be prohibited of producing micro blocks for the rest of the epoch and the corresponding validator will be inactivated at the end of the epoch.

Besides the obvious advantages of not having unpark transactions and being a simpler mechanism, there are other advantages:

- We punish validators that fork more harshly, which is desirable since forking is malicious behaviour while delaying can just happen due to network conditions.
- It eliminates the risk of a validator being continuously delaying and/or forking and then unparking. In this mechanism you can only misbehave a limited number of times and then you're out.
- We can have more fine-grained control over the punishments. We don't need to punish all delays with a fixed slash. We can, for example, punish the first delay 0.01 and then increase the punishment as more delays happen. Or any other function that we wish.

**Comment by redmaner** [comment]
Would this mechanism mean that the moment for reward payouts for validators is changed to once per epoch, compared to the current implementation which is once per batch? Not necessarily an issue but just an interesting point to know about.

**Comment by brunoffranca** [comment]
Yes. But note that this isn't decided at all, we still need to discuss it. I just wanted to put my thoughts in a more accessible place.

**Comment by paberr** [comment]
What is the impact on our security model? Should be more or less equivalent to the old model, right (validators that are offline for a short time do not lose all rewards, forking ones always lose all rewards)?

The main difference (which isn't an issue) seems to be that after being offline for a certain time, there's no way for a validator to join back in during this epoch.

**Comment by brunoffranca** [comment]
Right, the security model shouldn't really be affected. Validators still get punished, so that should still stop rational validators from misbehaving.

**Comment by brunoffranca** [comment]
There was some discussion but no conclusion yet. Two interesting points that were not considered before:

1. The unpark transaction mechanism disables validators as soon as they become unresponsive (with only one view change). In this respect it is more efficient than the proposed mechanism which will only disable validators after _n_ view changes.
2. Validators have conflicting incentives for accepting unpark transactions. On the one hand, they receive fees. On the other hand, increasing the parked validator's down time is good for them (pools compete with each other, more down time means less rewards and a lower Validator Trust Score). A rational validator would probably refuse to include an unpark transaction unless the fee is quite high.
