### ISSUE TITLE
StakingValidator sorted set inconsistency

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#56]
The `StakingContract` uses a `BTreeSet` to have all active stakes sorted. The ordering is ascending, yet the slot selection assumes descending balances:

```
        // Build potential validator set and find minimum stake.
        // Iterate from highest balance to lowest.
        for validator in self.active_stake_sorted.iter() {
```

This will be obsolete once we remove `min_stake`.

**Comment by paberr** [comment]
Fixed with #68 and #70.
