### ISSUE TITLE
Migrate to libp2p request/response

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#649]
- [x] Apply changes in network and document the API for network interface
- [x] Consensus changes to adapt to the new request /response 
- [x] Unittesting 
- [x] System testing
- [x] Re-implement direct sends in validator network
- [x] Remove network message dispatcher

**Comment by sisou** [comment]
Could you add a paragraph or two to describe _why_ this is necessary, or why you decided this?

**Comment by viquezclaudio** [comment]
@jsdanielh Can provide more details, but I can give it a try:
Currently we have our own implementation of the request/response functionality which has the following problems:

- There is a mutex that is being held for a super long period of time which is generating several problems/bugs all around the Nimiq client 

- Our code has functionality that we need to maintain and outsource to libp2p, and it doesn't make much sense to maintain our own version of something that is already provided by libp2p

**Comment by sisou** [comment]
Ah, I understand. I thought this was a move away from pub/sub to request/response. Didn't know it was a change from req/res to another implementation of req/res 👍
