### ISSUE TITLE
Ship core-rs-albatross logs directly to Loki

### ISSUE THREAD

**Issue by jeffesquivels** [nimiq/core-rs-albatross#665]
The best scenario would be for us to be able to ship logs directly from the application into the centralized log management system (Loki).

Theoretically this would be possible via GELF, since we have support for it since [this](https://github.com/nimiq/core-rs-albatross/commit/e91c7291349e2d53adb9035f8d293da9e967b67c) and Promtail (Loki's log shipping agent) added support for it on [this](https://github.com/grafana/loki/pull/4744/commits/234f34cfc19edf1f5ee416ea4a95f21085e3c6d1) commit.

There are two challenges, though:

- Although already it is already merged to `main`, GELF support in Promtail is not yet present in their latest release
- Our current implementation supports GELF through TCP and Promtail only supports GELF through UDP

**Comment by jeffesquivels** [comment]
> Our current implementation supports GELF through TCP and Promtail only supports GELF through UDP

This was easily solved as the crate we're using to send GELF logs (`tracing-gelf`) also supports doing so through UDP.

> Although already it is already merged to `main`, GELF support in Promtail is not yet present in their latest release

This was solved by compiling `promtail` from source code, but it would constantly log an `"json.Unmarshal: unexpected EOF"` error (even though most logs seemed to make it into Loki) so two other options were explored:

- Using [grayproxy](https://github.com/andviro/grayproxy) (which supports sending logs directly to Loki) instead of `promtail`, but this also logged an error when Loki parsed the logs sent to it.
- Using `graylog` itself as a proxy (ingesting the logs directly from the nodes and then sending them to `promtail` via a GELF UDP output).

None of these two options worked at all, so the option of sticking with `promtail` and fixing the errors we were seeing was explored, but it seems this is not easily done (it would require changing the GELF library they're using, see [this](https://github.com/grafana/loki/issues/5644) for details).

In the end, the easiest way to get this working (which is also the better one) is to implement a new tracing subscriber that ships the logs directly to Loki (similar to `tracing-gelf` but for Loki). This option is being worked on by @hrxi.

**Comment by hrxi** [comment]
Done by #703.
