### ISSUE TITLE
Investigate frequent gossip of outdated blocks

### ISSUE THREAD

**Issue by nibhar** [nimiq/core-rs-albatross#733]
A set of 2 distinct blocks were gossiped around thousands of times in a recent Devnet run. These Blocks are very outdated. Current head was #552928 with the gossiped Blocks being #446784.0 and #251968.0.

**Comment by viquezclaudio** [comment]
In the last devnet run there are many instances of:
`Discarding block #68320.0, we're already at macro block #884800`
