### ISSUE TITLE
MDBX UtterlyNoSync can corrupt database requiring resync from scratch

### ISSUE THREAD

**Issue by sisou** [nimiq/core-rs-albatross#750]
The MDBX database runs with `SyncMode::UtterlyNoSync`, with no option to configure it:
https://github.com/nimiq/core-rs-albatross/blob/7c2a7c25e26c3d4fcc5d123db3aa57ee2d09f750/database/src/mdbx.rs#L57-L63

This means in case of a system crash or simply stopping the client with CTRL+C at the wrong time, the database can get corrupted and become unusable, requiring wiping it and building it again from scratch.

The `UtterlyNoSync` sync mode has been set for performance reasons, but I believe for a production system this is not the correct setting.

My suggestion is to default to `SyncMode::SafeNoSync`, which prevents database corruption.

To benchmark the client, this setting may become configurable through the `client.toml` config, so that for performance tests the database bottleneck can be reduced.

**Comment by hrxi** [comment]
If I understand the docs correctly, it shouldn't corrupt on ctrl-c: https://docs.rs/libmdbx/latest/libmdbx/enum.SyncMode.html#variant.UtterlyNoSync

> A system crash immediately after commit the write transaction high likely lead to database corruption.

Or does "system" refer to the application, not the whole computer?

**Comment by sisou** [comment]
My database was corrupted this morning again, after having the laptop shut down over night. I was running with `SafeNoSync`, so it seems the problem is somewhere else. I use disk encryption on Linux, so that might have something to do with it, although trying to recreate the issue just now by syncing, stopping and restarting the laptop a couple times failed to reproduce the corruption.

Needs more experimentation.

**Comment by hrxi** [comment]
I also saw the corruption issue once, I also use disk encryption. I feel like disk encryption might be a red herring though.

**Comment by redmaner** [comment]
I've seen the corruption issue as well, but I don't use disk encryption
