### ISSUE TITLE
Building fork proofs

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#78]
Currently, our code doesn't check for forks.
We should however detect those, build fork proofs and send them to the network/include them into the chain.

**Comment by paberr** [comment]
We should use inv vectors for sending around fork proofs as they have 612 bytes.

**Comment by styppo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build fork proofs](https://trello.com/c/vHo6Is0A/3-build-fork-proofs)
