### ISSUE TITLE
Accounts::commit takes block number

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#83]
`Accounts::commit` takes a block number, but for macro-block-sync we don't exactly know that number. Currently `Blockchain::push_isolated_macro` uses the block number of the macro block. A full sync uses the block number if the actual micro block the transactions and inherents were in.

**Comment by brunoffranca** [comment]
Depending on the organization of our history root, we may actually have the block numbers for each transaction. But this is relevant for #18.
