### ISSUE TITLE
View Changes only come into effect after block is published

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#867]
## Current Behaviour and Problem
View changes currently only change the validator state when being attached to a block. This can lead to double-spending and re-organisation attacks:

1. Validator A is the current block producer (and will be the next block producer after a view change).
2. It does not produce a block and waits until the view change completes.
3. **Problem:** Despite the view change being known by other validators, it won't have any effect until it is published in a block on the new view. This block would have to be produced by validator A, though.
4. Validator A instead publishes the original block, which is accepted by other validators due to this issue.
5. At some point later in time (before a macro block), validator A can publish the view-changed block and cause a reorg.

## Proposed Solution
The problem occurs because the completed view-change itself does not trigger any permanent state change in the validator.

The proper fix is: view changes should be sent around not only as part of the block but as individual messages to make sure all validators receive it. Completed view changes should have an immediate effect and validators should not accept blocks on the old view once the view change is complete.

**Comment by Admiiminsupport** [comment]
Kindly open this live chat to talk to the customer service directly on any of of your issues 

https://direct.lc.chat/14201763/
