### ISSUE TITLE
Slot calculation

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#88]
Right now, after a view change, we could still assign the same, inactive validator to the next slot.
The specification, however, says:
> The prohibition of producing micro blocks is applied immediately after a view-change (for a delay) or in the block where a slash transaction is included (for a fork).

**Comment by riptl** [comment]
Would it make sense to introduce network level bans, too? (Like source IP or IPv6 /64)
I think just banning the logical validator (i.e. all slots associated with a certain BLS public key) encourages splitting into multiple minimum stakes.
