### ISSUE TITLE
Reward distribution

### ISSUE THREAD

**Issue by paberr** [nimiq/core-rs-albatross#89]
Right now, we distribute the reward equally between all non-misbehaving validators.
While this incentives reporting of forks, it also incentivises validators attacking each other to maximise their reward.

The current specification thus says:
> His reward is confiscated and burned\footnote{The reward is not divided among the other validators so as to not incentivize them to attack each other (ex: by doing a denial-of-service).}.

**Comment by brunoffranca** [comment]
Was this fixed with the staking changes PR?

**Comment by paberr** [comment]
> Was this fixed with the staking changes PR?

No
