### ISSUE TITLE
Inactivating delaying slot owners

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#9]
From our discussion:

Instead of slashing (with fine) misbehaving validators, we can deactivate all stakes of that slot owner. The deactivation of the stakes will be done after a grace period of 2 epochs. The slot owner than either has to:
 * Produce a block in the next epoch (where their stake is still active) - optional
 * Send a restaking transaction in the next epoch - this should be the default behavior

The restaking transaction can be done using a warm address that is linked to that stake. Thus the validator only needs to keep a private key of the warm wallet which only needs funds for transaction fees.

**Comment by paberr** [comment]
This only affects view changes.

**Comment by paberr** [comment]
Moreover, one question: Do these validators still get parts of the reward?

**Comment by paberr** [comment]
> Moreover, one question: Do these validators still get parts of the reward?

See #21: They won't get the reward for the particular slot.
