### ISSUE TITLE
Allow failing transactions

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#905]
Doing all checks in order to accept transactions into the mempool that would never fail is expensive, at least in performance/computational terms, since this would essentially require to simulate all the transactions to know wether they will succeed or not (which was the model used in our initial mempool implementation). 
Given our high throughput and performant requirements, this is no longer an option (doing a full commit check in the mempool) and thats why we moved away from this model. 
However there are still different cases (specially related to staking) that could fail when including a transaction into a block. 
Another possibility would be to do full checks during block production, but this would open a window for DoS attacks, which is something that we want to avoid. 
The desired solution is then to allow failing transactions, that is, if a transaction fails to be applied into the accounts state, we deduct fees and mark the transaction as a failed transaction. We anticipate this to not occur frequently, as this would happen when a user is using the staking contract incorrectly. 
To properly implement this functionality several changes need to take place:

- [ ] Create and implement a commit_failed / revert_failed APIs in the accounts interaction traits
- [ ] Create a wrapper around the Transaction struct that is included in a block to signal the success or failure or a given transaction
- [ ] Modify the accounts tree commit to operate on a per transaction atomicity basis
- [ ] Expose the result of applying individual transactions to the accounts tree
- [ ] Use the result of applying transactions as part of the block production process
- [ ] Use the result of applying transactions as part of the check/verification process when we receive a block
- [ ] Modify the history store to use the new transaction wrapper
- [ ] Create proper unit tests to test this new functionality

**Comment by sisou** [comment]
Does this affect regular transfers? In the following scenario, what happens?

- My account has 10 NIM balance
- I send a transaction transferring 100 NIM with 0 fees to another account

1. The transaction is included, 0 fees are deducted, nothing actually happens (but invalid tx spam in the block)
2. The transaction is included and a fee is deducted from my balance (how much)?
3. The transaction is rejected by the mempool

**Comment by viquezclaudio** [comment]
This does not affect regular transfers.
So in the above scenario #3 will occur, because we still check if the sender can pay the txn value + fee before accepting it into the mempool.
