### ISSUE TITLE
Automatic validator activation

### ISSUE THREAD

**Issue by viquezclaudio** [nimiq/core-rs-albatross#917]
The objective of this task is to create something similar to the automatic unpark functionality: If a validator is inactive, automatically send a transaction that will re-activate the validator. 
This functionality should be enabled/disabled via a config file option, since it is optional and the user should decide wether they want their own inactive validators to automatically activate themselves or not.

**Comment by sisou** [comment]
Is the use-case to be a failsafe in case the automatic unpark fails and the validator becomes inactive? Or is there another use case that you had in mind for this feature?

**Comment by viquezclaudio** [comment]
The primary use case is as a failsafe..

**Comment by ii-cruz** [comment]
Fixed in #937
