### ISSUE TITLE
Integer overflow in validator timeout

### ISSUE THREAD

**Issue by jgraef** [nimiq/core-rs-albatross#97]
```
DEBUG validator            | Completed view change to #128.1
thread 'tokio-runtime-worker-5' panicked at 'attempt to subtract with overflow', validator/src/validator.rs:377:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by jgraef** [comment]
I will fix this together with #54

**Comment by brunoffranca** [comment]
The relevant lines for this are https://github.com/nimiq/core-rs-albatross/blob/albatross/validator/src/validator.rs#L515-L516
This should be fixed together with the Tendermint Implementation.
@fiaxh @nibhar

**Comment by jgraef** [comment]
I can't find the error location anymore. Since the validator has been rewritten a lot, I'm going to close this.
